import {ECONOMY,DIFFICULTIES,VERSION} from './config.js?v=1.4.0';
import {currentUser} from './auth.js?v=1.4.0';
import {databaseService,readData,withDeadline} from './sdk.js?v=1.4.0';
let catalog=[];
export async function loadCatalog(){if(catalog.length)return catalog;const response=await fetch(`cosmeticos.json?v=${VERSION}`);if(!response.ok)throw new Error('No se cargó la tienda.');catalog=await response.json();return catalog;}
export const getCatalog=()=>catalog;
export const cosmetic=id=>catalog.find(item=>item.id===id);
export function requirementMet(item,profile){if(!item?.requisito)return false;const r=item.requisito;return r.tipo==='nivel'?(profile.nivel||1)>=r.valor:r.tipo==='logro'&&(profile.estadisticas?.logros||[]).includes(r.valor);}
export function matchReward(match,before={},after={}){if(match.personalizada)return {monedas:0,base:0,logros:0,niveles:0};const multiplier=DIFFICULTIES[match.dificultad]?.xp||1;const raw=match.modo==='race'?Math.floor((match.puntos||0)/ECONOMY.puntosCarrera)+(ECONOMY.puestos[(match.puesto||99)-1]||0):(match.pasillos||0)*(match.modo==='coop'?ECONOMY.coop:ECONOMY.solo)*multiplier;
 const base=Math.min(ECONOMY.maxPartida,Math.max(0,Math.floor(raw))),logros=(after.estadisticas?.logros||[]).filter(id=>!(before.estadisticas?.logros||[]).includes(id)).length,niveles=Math.max(0,(after.nivel||1)-(before.nivel||1));return {monedas:Math.min(ECONOMY.maxPartida,base+logros*ECONOMY.logro+niveles*ECONOMY.nivel),base,logros,niveles};}
// Saldo + movimiento + inventario se validan contra el catálogo del servidor, en un commit.
export async function acquireItem(id){const user=currentUser();if(!user)throw new Error('Inicia sesión.');await loadCatalog();const local=cosmetic(id);if(!local)throw new Error('Objeto no disponible.');const{r,db}=await databaseService();
 for(let attempt=0;attempt<4;attempt++){const p=(await readData(`users/${user.uid}`)).val();if(!p)throw new Error('Perfil no disponible.');if(p.inventario?.[id])throw new Error('Ya lo tienes.');const server=(await readData(`catalogo/${id}`)).val();if(!server)throw new Error('Carga el catálogo en Firebase.');
  if(server.precio!==local.precio||server.tipo!==local.tipo)throw new Error('Recarga la tienda.');const ownedByRequirement=!!server.requisito;if(ownedByRequirement&&!requirementMet(server,p))throw new Error('Requisito pendiente.');const cost=ownedByRequirement?0:server.precio,saldo=p.monedas||0;if(saldo<cost)throw new Error('Almas insuficientes.');
  const op=`compra-${crypto.randomUUID()}`,next=saldo-cost;try{await withDeadline(r.update(r.ref(db),{[`users/${user.uid}/monedas`]:next,[`users/${user.uid}/ultimaOperacion`]:op,[`users/${user.uid}/inventario/${id}`]:true,[`movimientos/${user.uid}/${op}`]:{tipo:ownedByRequirement?'desbloqueo':'compra',itemId:id,delta:-cost,saldo:next,fecha:r.serverTimestamp()}}));return {saldo:next,item:local};}catch(e){if(attempt===3)throw e;}}
}
export async function equipItem(id,type){const user=currentUser();if(!user)throw new Error('Inicia sesión.');if(id){const item=cosmetic(id);if(!item||item.tipo!==type)throw new Error('Objeto no disponible.');}if(!['marco','titulo','fondo'].includes(type))throw new Error('Tipo inválido.');const{r,db}=await databaseService();const previous=(await readData(`users/${user.uid}/equipado`)).val()||{};await withDeadline(r.set(r.ref(db,`users/${user.uid}/equipado`),{marco:'',titulo:'',fondo:'',...previous,[type]:id||''}));document.dispatchEvent(new CustomEvent('pasillo-cosmetics'));}
export function coinNode(value,label='Almas'){const node=document.createElement('span');node.className='coin-balance';const img=document.createElement('img');img.alt='';img.src=`assets/ui/moneda-64.webp?v=${VERSION}`;img.onerror=()=>{img.onerror=null;img.src=`assets/ui/moneda-64.png?v=${VERSION}`;};const amount=document.createElement('strong');amount.textContent=String(value||0);node.append(img,amount);node.setAttribute('aria-label',`${label}: ${value||0}`);return node;}
export function showReward(id,reward){const root=document.getElementById(id);if(!root)return;root.replaceChildren();const gained=document.createElement('span');gained.className='coins-earned';gained.textContent=`+${reward.monedas||0}`;root.append(gained,coinNode(reward.saldo||0));root.setAttribute('aria-label',`${reward.monedas||0} almas ganadas. Saldo ${reward.saldo||0}.`);}
