import {winningResult,populateDifficulties} from './difficulty.js?v=1.4.0';
import {setPortrait} from './monsters.js?v=1.4.0';
import {confusables} from './config.js?v=1.4.0';
// Misma instancia de lienzo, exportBlob y Recognizer. Sin llamadas a progreso ni récords.
export class Laboratory{
 constructor({drawing,recognizer,getMonsters,getLabels,onOpen,onClose}){Object.assign(this,{drawing,recognizer,getMonsters,getLabels,onOpen,onClose});this.active=false;this.sequence=0;this.results=[];this.$=id=>document.getElementById(id);const $=this.$;this.view=$('draw-view');this.home=this.view.parentNode;this.next=this.view.nextSibling;
 $('lab-back').onclick=()=>this.close();$('lab-analyze').onclick=()=>this.analyze();$('lab-auto').onchange=()=>{if($('lab-auto').checked)this.changed();else clearTimeout(this.autoTimer);};$('lab-target').onchange=()=>this.target();populateDifficulties($('lab-difficulty'));$('lab-difficulty').onchange=()=>this.target();$('lab-copy').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify({ms:this.inferenceMs,objetivo:Number($('lab-target').value)||null,dificultad:$('lab-difficulty').value,confusables,results:this.results.map(r=>({...r,nombre:this.getLabels().find(w=>w.id===r.label)?.nombre}))},null,2));$('lab-status').textContent='Copiado.';}catch{$('lab-status').textContent='No se pudo copiar.';}};
 }
 open(){this.active=true;this.sequence++;this.onOpen();this.$('lab-dock').append(this.view);this.view.hidden=false;this.drawing.enabled=true;this.drawing.clear(false);this.$('show').hidden=true;this.$('lab-status').textContent='';this.$('lab-results').replaceChildren();this.$('lab-verdict').textContent='';this.results=[];const select=this.$('lab-target');select.replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent='Sin objetivo';select.append(empty);for(const m of this.getMonsters()){const o=document.createElement('option');o.value=m.id;o.textContent=m.nombre;select.append(o);}this.$('lab-debug').hidden=new URLSearchParams(location.search).get('debug')!=='1';this.status(this.lastStatus||{state:this.recognizer.ready?'ready':'loading',percent:0});if(!this.recognizer.ready)this.recognizer.load().catch(()=>{});}
 detach(){this.active=false;this.sequence++;clearTimeout(this.autoTimer);this.drawing.cancel();this.drawing.enabled=false;this.home.insertBefore(this.view,this.next);this.$('show').hidden=false;}
 close(){this.detach();this.onClose();}
 changed(){if(!this.active)return;this.sequence++;this.$('lab-status').textContent='';clearTimeout(this.autoTimer);if(this.$('lab-auto').checked)this.autoTimer=setTimeout(()=>{if(this.drawing.active===null)this.analyze();else this.changed();},1000);}
 status(s){this.lastStatus=s;if(!this.active)return;this.$('lab-loading').hidden=s.state==='ready';this.$('lab-progress').value=s.percent||0;this.$('lab-progress-label').textContent=s.state==='error'?'No se cargó la IA.':`Cargando IA: ${s.percent||0} %`;this.$('lab-analyze').disabled=s.state!=='ready'||this.busy;}
 async analyze(){if(!this.active||this.busy)return;clearTimeout(this.autoTimer);const token=this.sequence;this.busy=true;this.$('lab-analyze').disabled=true;this.$('lab-status').textContent='Analizando…';try{const blob=await this.drawing.exportBlob();if(!blob){this.$('lab-status').textContent='No dibujaste nada.';this.results=[];this.render();return;}const start=performance.now(),results=await this.recognizer.classify(blob,this.getLabels());if(!this.active||token!==this.sequence)return;this.inferenceMs=Math.round(performance.now()-start);this.results=results;this.$('lab-status').textContent='';this.render();}catch(e){if(this.active)this.$('lab-status').textContent=e.message;}finally{this.busy=false;if(this.active){this.$('lab-analyze').disabled=!this.recognizer.ready;if(token!==this.sequence&&this.$('lab-auto').checked)this.changed();}}}
 render(){const $=this.$,labels=this.getLabels();$('lab-results').replaceChildren(...this.results.slice(0,5).map(item=>{const row=document.createElement('article'),name=document.createElement('span'),percent=document.createElement('strong'),bar=document.createElement('progress'),monsters=document.createElement('div');row.className='lab-result';name.textContent=labels.find(w=>w.id===item.label)?.nombre||item.label;percent.textContent=`${(item.score*100).toFixed(1)} %`;bar.max=1;bar.value=item.score;monsters.className='weak-monsters';for(const m of this.getMonsters().filter(m=>m.debilidades.some(w=>w.id===item.label))){const image=document.createElement('img');setPortrait(image,m);monsters.append(image);}row.append(name,percent,bar,monsters);return row;}));$('lab-all').textContent=this.results.map(r=>`${labels.find(w=>w.id===r.label)?.nombre||r.label}: ${(r.score*100).toFixed(3)} %`).join('\n');$('lab-inference').textContent=`${this.inferenceMs||0} ms · Confusables: ${confusables.map(id=>labels.find(w=>w.id===id)?.nombre||id).join(', ')}`;this.target();}
 target(){const $=this.$,monster=this.getMonsters().find(m=>m.id===Number($('lab-target').value));if(!monster||!this.results.length){$('lab-verdict').textContent='';$('lab-target-image').hidden=true;return;}setPortrait($('lab-target-image'),monster);$('lab-target-image').hidden=false;const win=winningResult(this.results,monster,$('lab-difficulty').value),best=win||this.results[0];$('lab-verdict').textContent=`${win?'✓':'✗'} · ${(best.score*100).toFixed(1)} %`;}
}
