import {VERSION,DIFFICULTIES} from './config.js?v=1.4.0';
import {SETTINGS_SCHEMA,DEFAULT_SETTINGS,normalizeSettings} from './settings-schema.js?v=1.4.0';
import {currentUser,changePassword,deleteAccount,signOut,authError} from './auth.js?v=1.4.0';
import {databaseService,readData,withDeadline} from './sdk.js?v=1.4.0';
const KEY='pasillo-settings-v5';let values={...DEFAULT_SETTINGS},stop=null,uid='',saveTimer,queue=Promise.resolve();
try{values=normalizeSettings(JSON.parse(localStorage.getItem(KEY)||JSON.stringify(JSON.parse(localStorage.getItem('pasillo-infinito-v1')||'{}').options||{})));}catch{}
export const getSettings=()=>({...values});
export const shortcut=(name,key)=>values[`key${name}`]===key.toLowerCase();
function localSave(){try{localStorage.setItem(KEY,JSON.stringify(values));if(!uid)localStorage.setItem(`${KEY}-guest`,JSON.stringify(values));}catch{}document.dispatchEvent(new CustomEvent('pasillo-settings',{detail:getSettings()}));}
export function setSettings(patch,{sync=true}={}){const next=normalizeSettings({...values,...patch}),keys=Object.keys(SETTINGS_SCHEMA).filter(k=>SETTINGS_SCHEMA[k].tipo==='key');if(new Set(keys.map(k=>next[k])).size!==keys.length)throw new Error('Atajo ya asignado.');values=next;localSave();if(sync&&uid){clearTimeout(saveTimer);saveTimer=setTimeout(()=>flushSettings().catch(error=>document.dispatchEvent(new CustomEvent('pasillo-toast',{detail:authError(error)}))),250);}return true;}
export function flushSettings(){clearTimeout(saveTimer);const owner=uid,snapshot=getSettings();if(!owner)return Promise.resolve();queue=queue.catch(()=>{}).then(async()=>{if(currentUser()?.uid!==owner)return;const{r,db}=await databaseService();await withDeadline(r.set(r.ref(db,`users/${owner}/ajustes`),snapshot));});return queue;}
export async function syncSettings(){stop?.();stop=null;clearTimeout(saveTimer);uid=currentUser()?.uid||'';if(!uid){try{values=normalizeSettings(JSON.parse(localStorage.getItem(`${KEY}-guest`)||'{}'));}catch{values={...DEFAULT_SETTINGS};}localSave();return;}
 const{r,db}=await databaseService(),ref=r.ref(db,`users/${uid}/ajustes`),snap=await readData(`users/${uid}/ajustes`);if(snap.exists())values=normalizeSettings(snap.val());else await r.set(ref,values);localSave();stop=r.onValue(ref,s=>{if(s.exists()){values=normalizeSettings(s.val());localSave();}});}
export function applySettings(audio){const s=getSettings();audio?.setOptions(s);const b=document.body;b.classList.toggle('reduced',s.flash==='reduced');b.classList.toggle('attenuated',s.screamer==='attenuated');b.classList.toggle('large-text',s.largeText);b.classList.toggle('high-contrast',s.highContrast);b.dataset.quality=s.quality;b.dataset.timerSize=s.timerSize;b.dataset.colorblind=s.colorblind;
 for(const key of ['grain','vignette','fog','scanlines','chromatic'])b.classList.toggle(`effect-${key}`,s[key]);b.style.setProperty('--shake',s.shake);document.getElementById('mute').textContent=s.muted?'ACTIVAR SONIDO':'SILENCIAR';}
const labels={facil:'Fácil',normal:'Normal',dificil:'Difícil',pesadilla:'Pesadilla',reduced:'Reducido',attenuated:'Atenuado',hard:'Duro',soft:'Suave',pencil:'Lápiz',marker:'Marcador',spray:'Aerosol',stamp:'Caligrafía',brush:'Pincel',eraser:'Goma',fill:'Relleno',eyedropper:'Cuentagotas',line:'Línea',rectangle:'Rectángulo',ellipse:'Elipse',triangle:'Triángulo',star:'Estrella',heart:'Corazón',arrow:'Flecha',no:'Desactivado'};
export function setupSettings({audio,getProfile,onAccess,onExit,onReset}){const $=id=>document.getElementById(id),modal=$('settings-modal'),content=$('settings-content');let category='audio',openReturn=()=>{};
 function row(key,s){const label=document.createElement('label');label.className='setting-row';label.htmlFor=`setting-${key}`;const name=document.createElement('span');name.textContent=s.nombre;let input;
 if(s.tipo==='select'){input=document.createElement('select');s.opciones.forEach(v=>{const option=document.createElement('option');option.value=v;option.textContent=labels[v]||String(v);input.append(option);});input.value=values[key];}
 else{input=document.createElement('input');input.type=s.tipo==='boolean'?'checkbox':s.tipo==='range'?'range':'text';if(s.tipo==='range'){input.min=s.min;input.max=s.max;input.step=.01;input.value=values[key];}else if(s.tipo==='boolean')input.checked=values[key];else{input.maxLength=1;input.value=values[key];}}
 input.id=`setting-${key}`;input.onchange=()=>{try{const v=s.tipo==='boolean'?input.checked:s.tipo==='range'||typeof s.valor==='number'?Number(input.value):input.value.toLowerCase();setSettings({[key]:v});if(!uid)try{localStorage.setItem(`${KEY}-guest`,JSON.stringify(values));}catch{}$('settings-status').textContent=uid?'Guardando…':'Guardado.';flushSettings().then(()=>$('settings-status').textContent='Guardado.').catch(e=>$('settings-status').textContent=authError(e));}catch(e){$('settings-status').textContent=e.message;render();}};label.append(name,input);if(s.tipo==='range'){const out=document.createElement('output');out.textContent=Math.round(values[key]*100)+' %';input.oninput=()=>out.textContent=Math.round(Number(input.value)*100)+' %';label.append(out);}return label;}
 const button=(text,click)=>{const b=document.createElement('button');b.textContent=text;b.onclick=click;return b;};
 function render(){for(const b of $('settings-nav').children)b.classList.toggle('active',b.dataset.category===category);content.replaceChildren();$('settings-status').textContent='';const p=getProfile(),user=currentUser();$('settings-reset').hidden=category==='cuenta'&&!user;
 if(category==='cuenta'){if(!user){content.append(button('INICIAR SESIÓN',()=>{close();onAccess('login');}),button('CREAR CUENTA',()=>{close();onAccess('register');}));return;}
  const identity=document.createElement('p');identity.textContent=`🔒 ${p.nombre} · ${user.email?.replace(/^(.{1,2}).*(@.*)$/,'$1•••$2')||''}`;content.append(identity);
  content.append(button('COPIAR CÓDIGO',()=>copy(p.codigoAmigo)),button('COPIAR ENLACE',()=>{const url=new URL(location.href);url.search='';url.searchParams.set('amigo',p.codigoAmigo);copy(url.href);}));
  for(const[key,name,type]of [['solicitudes','Recibir solicitudes','boolean'],['estadoVisible','Mostrar estado en línea','boolean'],['perfil','Quién ve mi perfil','select'],['invitaciones','Recibir invitaciones','boolean']]){const s={nombre:name,tipo:type,opciones:['todos','amigos'],valor:true},label=row(key,{...s,categoria:'cuenta'}),input=label.querySelector('input,select');if(type==='boolean')input.checked=p.preferencias?.[key]!==false;else input.value=p.preferencias?.[key]||'todos';input.onchange=async()=>{try{const{r,db}=await databaseService();await r.set(r.ref(db,`users/${user.uid}/preferencias/${key}`),type==='boolean'?input.checked:input.value);document.dispatchEvent(new CustomEvent('pasillo-privacy'));$('settings-status').textContent='Guardado.';}catch(e){$('settings-status').textContent=authError(e);}};content.append(label);}
  const form=document.createElement('form');form.id='password-form';form.className='account-form';form.innerHTML='<label for="current-password">Contraseña actual</label><input id="current-password" type="password" autocomplete="current-password" required><label for="new-password">Nueva contraseña</label><input id="new-password" type="password" autocomplete="new-password" minlength="8" required><button type="submit">CAMBIAR CONTRASEÑA</button>';form.onsubmit=async e=>{e.preventDefault();try{await changePassword($('current-password').value,$('new-password').value);form.reset();$('settings-status').textContent='Contraseña cambiada.';}catch(e){$('settings-status').textContent=authError(e);}};content.append(form);
  // Un guardado rechazado por borrado en curso o red caída no debe impedir salir de Auth.
  content.append(button('CERRAR SESIÓN',async()=>{try{await flushSettings().catch(()=>{});await signOut();close();onExit();}catch(e){$('settings-status').textContent=authError(e);}}));
  const remove=document.createElement('form');remove.className='account-form';remove.innerHTML='<label for="delete-name">Escribe tu nombre</label><input id="delete-name" autocomplete="off" required><label for="delete-password">Contraseña actual</label><input id="delete-password" type="password" autocomplete="current-password" required><button id="delete-account" class="danger" type="submit">ELIMINAR CUENTA</button>';remove.onsubmit=async e=>{e.preventDefault();if($('delete-name').value!==p.nombre){$('settings-status').textContent='El nombre no coincide.';return;}const b=$('delete-account');b.disabled=true;try{await deleteAccount($('delete-password').value);close();onExit();}catch(e){$('settings-status').textContent=authError(e);}finally{b.disabled=false;}};content.append(remove);
 }else if(category==='datos'){const info=document.createElement('p');info.textContent=`Versión ${VERSION} · Arte: ChatGPT · Audio: síntesis original · CLIP / Transformers.js · Pirata One, IM Fell English y Cutive Mono: OFL 1.1`;content.append(info,button('BORRAR RÉCORDS LOCALES',()=>document.dispatchEvent(new CustomEvent('pasillo-clear-local'))),button('RESTABLECER TODO',async()=>{setSettings(DEFAULT_SETTINGS);await flushSettings();onReset?.();render();}));}
 else{for(const[key,s]of Object.entries(SETTINGS_SCHEMA))if(s.categoria===category)content.append(row(key,s));if(category==='audio')content.append(button('PROBAR SONIDO',async()=>{await audio.start();audio.effect('count');}));if(category==='calidad')content.append(button('PANTALLA COMPLETA',async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen();}catch{$('settings-status').textContent='No disponible.';}}));}
 }
 async function copy(value){try{await navigator.clipboard.writeText(value);$('settings-status').textContent='Copiado.';}catch{$('settings-status').textContent='No se pudo copiar.';}}
 function close(){if(modal.open)modal.close();openReturn();openReturn=()=>{};}
 $('settings-close').onclick=close;modal.addEventListener('cancel',e=>{e.preventDefault();close();});
 for(const b of $('settings-nav').children)b.onclick=()=>{category=b.dataset.category;render();};
 $('settings-reset').onclick=async()=>{try{if(category==='cuenta'&&currentUser()){const{r,db}=await databaseService();await r.set(r.ref(db,`users/${currentUser().uid}/preferencias`),{solicitudes:true,estadoVisible:true,perfil:'todos',invitaciones:true});document.dispatchEvent(new CustomEvent('pasillo-privacy'));}else{const patch=Object.fromEntries(Object.entries(SETTINGS_SCHEMA).filter(([,s])=>s.categoria===category).map(([k,s])=>[k,s.valor]));setSettings(patch);await flushSettings();}render();}catch(e){$('settings-status').textContent=authError(e);}};
 return {open:(back=()=>{})=>{openReturn=back;render();modal.showModal();},close,render};
}
