// Pruebas reales de interfaz y SDK contra Auth/RTDB locales.
// Solo la inferencia CLIP se sustituye por resultados controlados.
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {server,setup,state,bg,ink,fonts,shots,errors,primary,browserOptions,forbiddenServices}=require('./ui.cjs');const {chromium}=require(primary+'/playwright');
const {runtime}=require('./ui.cjs'),testRequire=require('node:module').createRequire(runtime+'/firebase-admin/package.json');const {initializeApp,deleteApp}=testRequire('firebase-admin/app');const {getDatabase}=testRequire('firebase-admin/database');
const monsters=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../monsters.json'))),accounts=[];
async function register(page,name,avatar=1){await page.click('#auth-register');await page.fill('#auth-name',name);await page.fill('#auth-email',name.toLowerCase()+'@example.invalid');await page.fill('#auth-password','Prueba12345');await page.click('#auth-submit');await state(page,'menu');if(avatar!==1){await page.click('#profile-open');await page.click(`#avatar-grid button[data-id="${avatar}"]`);await page.click('#save-avatar');await page.waitForFunction(()=>document.getElementById('profile-status').textContent==='Guardado.');await page.click('#profile-back');}accounts.push(name);}
async function startSolo(page,d='normal',seed=''){await page.click('#play');await page.click('#solo-mode');await state(page,'preparation');await page.selectOption('#prep-difficulty',d);await page.fill('#prep-seed',seed);await page.click('#prep-start');await state(page,'count');}
async function recognizeOwn(page){const info=await page.locator('#monster-face').getAttribute('src'),m=monsters.find(m=>info?.includes(m.imagen));assert(m,info);await page.evaluate(label=>window.__label=label,m.debilidades[0].etiquetaCLIP);return m;}
async function loseEmpty(page){await page.click('#tab-draw');await page.click('#clear');await page.click('#show');await state(page,'lose');await state(page,'over');await page.waitForFunction(()=>document.getElementById('save-status').textContent!=='Guardando…');}
(async()=>{
 await new Promise(resolve=>server.listen(8002,'127.0.0.1',resolve));const browser=await chromium.launch(browserOptions);
 const {initializeTestEnvironment}=require(runtime+'/@firebase/rules-unit-testing');const env=await initializeTestEnvironment({projectId:'demo-pasillo',database:{host:'127.0.0.1',port:9000,rules:fs.readFileSync(path.resolve(__dirname,'../database.rules.json'),'utf8')}});
 const app=initializeApp({projectId:'demo-pasillo',databaseURL:'https://demo-pasillo.firebaseio.com',credential:{getAccessToken:async()=>({access_token:'owner',expires_in:3600})}},'ui-admin'),rt=getDatabase(app);const report=[];const note=text=>{report.push(text);console.log('OK:',text);};
 try {
  await env.clearDatabase();
  const guestContext=await browser.newContext({viewport:{width:1440,height:1000}}),guest=await setup(guestContext);await fonts(guest);await guest.click('#auth-guest');await state(guest,'menu');assert(await guest.locator('#profile-open').isHidden());assert(await guest.locator('#friends-open').isHidden());await guest.evaluate(()=>window.__backgroundNode=document.getElementById('corridor'));
  for(let run=0;run<Number(process.env.PASILLO_QA_GUEST_RUNS??3);run++){await startSolo(guest,'normal','tres-partidas');await bg(guest,`cuenta ${run+1}`);await state(guest,'flash');await bg(guest,`flash ${run+1}`);await state(guest,'book');await bg(guest,`libro ${run+1}`);await recognizeOwn(guest);await ink(guest);await bg(guest,`lienzo ${run+1}`);await guest.click('#show');await state(guest,'suspense');await bg(guest,`suspenso ${run+1}`);await state(guest,'win');await bg(guest,`victoria ${run+1}`);await state(guest,'book');await loseEmpty(guest);await bg(guest,`muerte ${run+1}`);assert.equal(await guest.locator('#final-score').textContent(),'1');assert.equal(await guest.locator('#save-form').count(),0);await guest.click('#back-menu');await bg(guest,`menú ${run+1}`);}
  assert.equal(Object.keys((await rt.ref('users').get()).val()||{}).length,0);note(`Invitado: solo/local; ${Number(process.env.PASILLO_QA_GUEST_RUNS??3)} partidas completas con fondo persistente; sin perfil, XP ni récord global.`);
  await guest.setViewportSize({width:390,height:844});await startSolo(guest,'facil','lienzo');await state(guest,'book');await fonts(guest);assert.equal(await guest.locator('#timer').textContent(),'75');await guest.screenshot({path:path.join(shots,'v13-book-mobile.png'),fullPage:true});await guest.click('#tab-draw');await fonts(guest);assert.equal(await guest.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await guest.screenshot({path:path.join(shots,'v13-draw-mobile.png'),fullPage:true});
  // Validación de la capa temporal y exportación sobre blanco con color.
  const drawingInfo=await guest.evaluate(async()=>{const {Drawing}=await import('/js/draw.js?v=1.4.0');const c=document.createElement('canvas');c.width=c.height=512;c.getBoundingClientRect=()=>({left:0,top:0,width:512,height:512});c.setPointerCapture=()=>{};const d=new Drawing(c);d.enabled=true;d.color='#ff0000';d.opacity=.5;d.size=30;
    const event=(x,y)=>({pointerId:1,pointerType:'mouse',button:0,clientX:x,clientY:y,preventDefault(){},shiftKey:false});d.down(event(200,200));for(let i=0;i<20;i++){d.move(event(210,200));d.move(event(200,200));}d.end(event(200,200));const pixel=[...d.ix.getImageData(200,200,1,1).data];const blob=await d.exportBlob();const image=await createImageBitmap(blob),out=document.createElement('canvas');out.width=out.height=256;const ctx=out.getContext('2d');ctx.drawImage(image,0,0);const white=[...ctx.getImageData(0,0,1,1).data];image.close();d.undo();const undone=[...d.ix.getImageData(200,200,1,1).data];d.redo();const redone=[...d.ix.getImageData(200,200,1,1).data];
    for(let i=0;i<35;i++){d.snapshot();d.ix.fillStyle='#000';d.ix.fillRect(i*3,300,2,2);}const history=d.history.length;d.undo();d.redo();
    d.clear(false);d.ix.fillStyle='#000';d.ix.fillRect(180,180,100,100);d.ix.fillRect(0,0,1,1);d.ix.fillRect(510,510,1,1);const bounds=d.bounds();return {pixel,white,undone,redone,history,bounds};});
  assert.equal(drawingInfo.pixel[0],255);assert.equal(drawingInfo.pixel[3],255);assert(Math.abs(drawingInfo.pixel[1]-127)<=2&&Math.abs(drawingInfo.pixel[2]-127)<=2);assert.deepEqual(drawingInfo.white,[255,255,255,255]);assert.deepEqual(drawingInfo.undone,[255,255,255,255]);assert.deepEqual(drawingInfo.redone,drawingInfo.pixel);assert(drawingInfo.history>=30);assert(drawingInfo.bounds.x>100&&drawingInfo.bounds.w<130);
  await guest.locator('.tools details').filter({has:guest.locator('#brush-kind')}).evaluate(el=>el.open=true);
  for(const kind of ['hard','soft','pencil','marker','spray','stamp']){await guest.selectOption('#brush-kind',kind);await ink(guest);}
  await guest.locator('.tools details').filter({has:guest.locator('.shape-buttons')}).evaluate(el=>el.open=true);
  for(const tool of ['line','rectangle','ellipse','triangle','star','heart','arrow']){await guest.click(`[data-tool="${tool}"]`);await ink(guest);}
  await guest.locator('.tools details').filter({has:guest.locator('#symmetry')}).evaluate(el=>el.open=true);await guest.check('#symmetry');await guest.click('[data-tool="eraser"]');await ink(guest);await guest.click('#undo');await guest.click('#redo');await guest.click('[data-tool="fill"]');await guest.locator('#drawing').click({position:{x:10,y:10}});await guest.click('[data-tool="eyedropper"]');await guest.locator('#drawing').click({position:{x:10,y:10}});
  await fonts(guest);note('Lienzo: seis pinceles, siete formas, goma/cubo/cuentagotas/simetría, capa al 50 %, 35 pasos, recorte de spray y exportación PNG en color blanco opaco.');
  await guest.click('#pause');await guest.click('#quit');await guest.reload();await guest.click('#accept');await guest.click('#auth-guest');await guest.evaluate(()=>window.__backgroundNode=document.getElementById('corridor'));await bg(guest,'F5');
  await guest.evaluate(()=>{document.getElementById('corridor').style.backgroundImage='none';document.dispatchEvent(new Event('visibilitychange'));});await bg(guest,'evento de visibilidad');await guest.setViewportSize({width:820,height:920});await bg(guest,'redimensionado');await guestContext.close();
  const fallbackContext=await browser.newContext({viewport:{width:1000,height:800}});await fallbackContext.route('**/assets/ui/pasillo-*.webp*',route=>route.abort());const fallback=await setup(fallbackContext);await bg(fallback,'acceso con imagen fallida',false);await fallback.click('#auth-guest');await bg(fallback,'menú con imagen fallida',false);await fallbackContext.close();note('Fondo: F5, redimensionado, evento de visibilidad y degradado cuando fallan las imágenes.');
  const context=await browser.newContext({viewport:{width:1360,height:1000}}),page=await setup(context);await register(page,'Ana13',12);await page.click('#profile-open');assert.equal(await page.locator('#avatar-grid button').count(),12);assert.equal(await page.locator('#bestiary figure').count(),monsters.length);assert.equal(await page.locator('#achievements>span').count(),13);assert.equal(await page.locator('#profile-name').evaluate(el=>el.tagName),'H2');await fonts(page);await page.click('#profile-back');await page.reload();await page.click('#accept');await state(page,'menu');await page.evaluate(()=>window.__backgroundNode=document.getElementById('corridor'));assert((await page.locator('#menu-profile').textContent()).includes('Ana13'));
  const uid=await page.evaluate(async()=>{const {currentUser}=await import('/js/auth.js?v=1.4.0');return currentUser().uid;});assert.equal((await rt.ref(`users/${uid}`).get()).val().avatar,12);await rt.ref(`users/${uid}`).update({xp:75,nivel:1});
  await startSolo(page,'normal');await state(page,'book');await recognizeOwn(page);await ink(page);await page.click('#show');await state(page,'win');await state(page,'book');await loseEmpty(page);await page.waitForFunction(()=>document.getElementById('save-status').textContent.includes('guardado'));assert.equal(Object.keys((await rt.ref('records_solo_normal').get()).val()||{}).length,1);assert((await rt.ref(`users/${uid}`).get()).val().xp>=10);await page.click('#back-menu');
  const publishing=await page.evaluate(async()=>{const {publishRecord}=await import('/js/records.js?v=1.4.0');return [await publishRecord({puntuacion:8}),await publishRecord({puntuacion:3}),await publishRecord({puntuacion:2,dificultad:'facil'})];});assert(publishing.every(r=>r.status==='global'));assert.equal(Object.keys((await rt.ref('records_solo_normal').get()).val()||{}).length,1);assert.equal((await rt.ref(`records_solo_normal/${uid}`).get()).val().puntuacion,8);
  // 55 registros mayores fuerzan un puesto propio fuera del top 50.
  const patch={};for(let n=0;n<55;n++)patch[`records_solo_normal/fake${n}`]={uid:'fake'+n,nombre:'Otro'+n,avatar:1,nivel:1,puntuacion:20+n,fecha:Date.now(),dificultad:'normal'};await rt.ref().update(patch);
  await page.click('[data-dialog="records"]');await page.waitForFunction(()=>document.querySelectorAll('#global-list li').length===51);assert((await page.locator('#global-list .own .rank').textContent())==='56');await fonts(page);await page.selectOption('#scores-difficulty','facil');await page.waitForFunction(()=>document.querySelectorAll('#global-list li').length===1);await page.click('#close-modal');note('Cuenta persistente, avatar 12, bestiario/logros, XP, récord único/mejor, dificultad y puesto 56 por conteo.');
  const secondContext=await browser.newContext({viewport:{width:1280,height:900}}),second=await setup(secondContext);await second.click('#auth-register');await second.fill('#auth-name','ANA13');await second.fill('#auth-email','bob13@example.invalid');await second.fill('#auth-password','Prueba12345');await second.click('#auth-submit');await second.waitForFunction(()=>document.getElementById('auth-status').textContent.includes('uso'));await register(second,'Bob13',10);const bobUid=await second.evaluate(async()=>{const {currentUser}=await import('/js/auth.js?v=1.4.0');return currentUser().uid;});
  await page.click('#friends-open');await page.fill('#friend-tag','@bOB13');await page.click('#friend-form button');await second.click('#friends-open');await second.waitForFunction(()=>document.querySelector('#friends-list')?.textContent.includes('ACEPTAR'));await second.getByRole('button',{name:'ACEPTAR',exact:true}).click();await page.waitForFunction(()=>document.getElementById('friends-list').textContent.includes('ELIMINAR'));assert.equal((await rt.ref(`social/${uid}/confirmados/${bobUid}`).get()).val(),true);
  await page.click('#friends-back');await page.click('[data-dialog="records"]');await page.selectOption('#scores-filter','friends');await page.waitForFunction(()=>document.querySelectorAll('#global-list li').length===1);await page.click('#close-modal');
  await page.click('#play');await page.click('#race-mode');await page.click('#create-room');await state(page,'preparation');await page.selectOption('#prep-difficulty','dificil');await page.click('#prep-start');await state(page,'lobby');const code=await page.locator('#room-code').textContent();await page.getByText('Invitar amigos',{exact:true}).click();await page.locator('#invite-friends').locator('button', {hasText:'INVITAR'}).click();await second.waitForFunction(()=>!document.getElementById('invitation-notice').hidden).catch(async e=>{console.error('Invitación',await page.locator('#toast').textContent(),(await rt.ref('invitaciones').get()).val());throw e;});await second.click('#invitation-accept');await state(second,'lobby');await second.waitForFunction(()=>document.querySelectorAll('#players li').length===2);assert.equal(await second.locator('#room-difficulty').inputValue(),'dificil');assert(await second.locator('#room-difficulty').isDisabled());
  await page.selectOption('#room-difficulty','pesadilla');await second.waitForFunction(()=>document.getElementById('room-difficulty').value==='pesadilla');await page.click('#ready-room');await second.click('#ready-room');await page.waitForFunction(()=>!document.getElementById('start-room').disabled);await page.click('#start-room');await state(page,'book');await state(second,'book');assert.equal(await page.locator('#monster-face').getAttribute('src'),await second.locator('#monster-face').getAttribute('src'));assert(Number(await page.locator('#timer').textContent())<=40);await page.click('#tab-draw');await second.click('#tab-draw');await page.click('#show');await second.click('#show');await state(page,'podium');await state(second,'podium');note('Amistad por etiqueta, vínculo mutuo, filtro Amigos, invitación instantánea y carrera en Pesadilla con una vida.');
  await page.click('#podium-leave');await second.click('#podium-leave');
  // Link de amistad recibido sin sesión: se conserva hasta el acceso.
  const thirdContext=await browser.newContext({viewport:{width:1280,height:900}}),third=await setup(thirdContext);const friendCode=(await rt.ref(`users/${uid}`).get()).val().codigoAmigo;await third.goto('http://127.0.0.1:8002/?amigo='+friendCode);await third.click('#accept');await state(third,'access');await register(third,'Cara13',9);assert.equal((await rt.ref(`social/${uid}/pendientes/${await third.evaluate(async()=>{const {currentUser}=await import('/js/auth.js?v=1.4.0');return currentUser().uid;})}`).get()).val().de,await third.evaluate(async()=>{const {currentUser}=await import('/js/auth.js?v=1.4.0');return currentUser().uid;}));note('Link personal conservado antes del acceso y solicitud completada tras crear la cuenta.');
  // Una victoria y una derrota cooperativas ejercitan los tres roles, la bolsa común y el récord de equipo.
  await page.click('#play');await page.click('#coop-mode');await page.click('#create-room');await page.selectOption('#prep-difficulty','pesadilla');await page.click('#prep-start');await state(page,'lobby');const coopCode=await page.locator('#room-code').textContent();
  for(const [i,player]of [second,third].entries()){await player.click('#play');await player.click('#coop-mode');await player.fill('#room-input',coopCode);await player.click('#join-form button');await player.waitForFunction(n=>document.querySelectorAll('#players li').length===n,i+2);}
  await page.selectOption('#role-choice','vigia');await second.selectOption('#role-choice','bibliotecario');await third.selectOption('#role-choice','dibujante');for(const player of [page,second,third])await player.click('#ready-room');await page.waitForFunction(()=>!document.getElementById('start-room').disabled);await page.click('#start-room');
  await state(third,'book');assert(await third.locator('#book-view').isHidden());assert(await second.locator('#draw-view').isHidden());const m=await recognizeOwn(page);await third.evaluate(label=>window.__label=label,m.debilidades[0].etiquetaCLIP);
  // Un trazo largo atraviesa varios refrescos de roles sin cancelarse ni quedar vacío.
  const canvasBox=await third.locator('#drawing').boundingBox();await third.mouse.move(canvasBox.x+canvasBox.width*.2,canvasBox.y+canvasBox.height*.2);await third.mouse.down();await third.evaluate(()=>window.__strokeStarted=performance.now());for(let i=1;i<=30;i++){await third.mouse.move(canvasBox.x+canvasBox.width*(.2+i/60),canvasBox.y+canvasBox.height*(.2+i/60));}await third.waitForFunction(()=>performance.now()-window.__strokeStarted>=600);await third.mouse.up();await third.click('#show');
  await state(page,'win');assert.equal((await rt.ref(`rooms/${coopCode}/meta/pasillos`).get()).val(),1);
  await state(page,'reveal');await state(third,'reveal');await bg(page,'revelado cooperativo');await fonts(page);await state(second,'book').catch(async error=>{const room=(await rt.ref(`rooms/${coopCode}`).get()).val();console.error('Diagnóstico de rotación',JSON.stringify({meta:room.meta,verdicts:room.veredictos,screens:await Promise.all([page,second,third].map(p=>p.evaluate(()=>({state:document.body.dataset.state,role:document.getElementById('active-role').textContent,toast:document.getElementById('toast').textContent,clock:document.getElementById('timer').textContent}))))}));throw error;});
  assert.equal(await page.locator('#active-role').textContent(),'Bibliotecario');assert.equal(await second.locator('#active-role').textContent(),'Dibujante');assert.equal(await third.locator('#active-role').textContent(),'Vigía');
  assert(await page.locator('#draw-view').isHidden());assert(await second.locator('#draw-view').isVisible());await second.click('#show');await state(page,'podium');await state(second,'podium');await state(third,'podium');await page.waitForFunction(()=>document.getElementById('online-save-status').textContent.includes('guardado'));assert.equal(Object.keys((await rt.ref('records_coop_pesadilla').get()).val()||{}).length,1);const team=Object.values((await rt.ref('records_coop_pesadilla').get()).val())[0];assert.equal(team.miembros.length,3);assert.equal(team.puntuacion,1);note('Cooperativo: tres roles, acierto, rotación, derrota, XP y un solo récord del equipo.');
  for(const player of [page,second,third])await player.click('#podium-leave');
  await page.click('#settings-open');await page.click('[data-category="cuenta"]');await page.getByRole('button',{name:'CERRAR SESIÓN',exact:true}).click();await state(page,'access');await page.fill('#auth-email','ana13@example.invalid');await page.fill('#auth-password','Prueba12345');await page.click('#auth-submit');await state(page,'menu');await page.click('#settings-open');await page.click('[data-category="cuenta"]');await page.fill('#current-password','Prueba12345');await page.fill('#new-password','Nueva12345');await page.click('#password-form button');await page.waitForFunction(()=>document.getElementById('settings-status').textContent.includes('cambiada'));await page.fill('#delete-name','Ana13');await page.fill('#delete-password','Nueva12345');await page.click('#delete-account');await state(page,'access');assert(!(await rt.ref(`users/${uid}`).get()).exists());assert(!(await rt.ref(`usernames/ana13`).get()).exists());assert(!(await rt.ref(`records_solo_normal/${uid}`).get()).exists());assert(!(await rt.ref(`social/${bobUid}/confirmados/${uid}`).get()).exists());note('Inicio/cierre de sesión, cambio de contraseña y eliminación completa desde la interfaz.');
  assert.deepEqual(errors,[]);assert.deepEqual(forbiddenServices,[]);note('Registro, sesión, partidas y ranking sin solicitudes a Functions ni Firestore.');const result={version:'1.4.0',report,pageErrors:errors,forbiddenServices,guestRuns:Number(process.env.PASILLO_QA_GUEST_RUNS??3),CLIP:'doble de prueba; inferencia real pendiente de validación visual humana'};fs.writeFileSync(path.resolve(__dirname,'../PRUEBAS-RESULTADOS.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
  await context.close();await secondContext.close();await thirdContext.close();
 }finally{await browser.close();server.close();await deleteApp(app);await env.cleanup();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
