// Compras, recibos, preferencias y ajustes con SDK cliente real y reglas activas.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),runtime=process.env.PASILLO_TEST_MODULES||(fs.existsSync(path.join(root,'node_modules/firebase'))?path.join(root,'node_modules'):path.resolve(root,'../qa-runtime/node_modules'));
const {initializeTestEnvironment,assertSucceeds,assertFails}=require(runtime+'/@firebase/rules-unit-testing'),db=require(runtime+'/firebase/database');
(async()=>{
 const {emptyStats,updatedStats,setMonsterCatalog,matchXp,levelFor}=await import('../js/xp.js');const {matchReward}=await import('../js/economy.js');const {DEFAULT_SETTINGS}=await import('../js/settings-schema.js');
 const monsters=JSON.parse(fs.readFileSync(path.join(root,'monsters.json'))),catalog=JSON.parse(fs.readFileSync(path.join(root,'cosmeticos.json')));setMonsterCatalog(monsters);
 const env=await initializeTestEnvironment({projectId:'demo-pasillo',database:{host:'127.0.0.1',port:9000,rules:fs.readFileSync(path.join(root,'database.rules.json'),'utf8')}}),report=[];
 const contexts=new Map(),ctx=id=>{if(!contexts.has(id))contexts.set(id,env.authenticatedContext(id,{firebase:{sign_in_provider:'password'}}).database());return contexts.get(id);};
 const get=async(id,p)=>(await db.get(db.ref(ctx(id),p))).val(),set=(id,p,v)=>db.set(db.ref(ctx(id),p),v),patch=(id,v)=>db.update(db.ref(ctx(id)),v),seed=v=>env.withSecurityRulesDisabled(c=>db.update(db.ref(c.database()),v));
 const note=text=>{report.push(text);console.log('OK:',text);};
 const create=(id,name,code,extra={})=>patch(id,{[`users/${id}`]:{nombre:name,nombreLower:name.toLowerCase(),avatar:1,xp:0,nivel:1,codigoAmigo:code,creadoEn:db.serverTimestamp(),estadisticas:emptyStats(),preferencias:{solicitudes:true,estadoVisible:true,perfil:'todos',invitaciones:true},ultimaPartida:'',monedas:0,ultimaOperacion:'',equipado:{marco:'',titulo:'',fondo:''},...extra},[`usernames/${name.toLowerCase()}`]:id,[`friendcodes/${code}`]:id,[`socialCounts/${id}`]:{amigos:0,pendientes:0,otroUid:'',accion:'crear',fecha:db.serverTimestamp()}});
 async function reward(id,match){const p=await get(id,`users/${id}`),xp=p.xp+matchXp(match),nivel=levelFor(xp).nivel,estadisticas=updatedStats(p.estadisticas,match),earned=matchReward(match,p,{nivel,estadisticas}),saldo=p.monedas+earned.monedas,op='partida-'+match.id;
  return {[`users/${id}/xp`]:xp,[`users/${id}/nivel`]:nivel,[`users/${id}/estadisticas`]:estadisticas,[`users/${id}/ultimaPartida`]:match.id,[`users/${id}/monedas`]:saldo,[`users/${id}/ultimaOperacion`]:op,[`partidas/${id}/${match.id}`]:{xp:xp-p.xp,fecha:db.serverTimestamp(),modo:match.modo,dificultad:match.dificultad,monedas:earned.monedas,baseMonedas:earned.base,pasillos:match.pasillos||0,puntos:match.puntos||0,puesto:match.puesto||99,logrosNuevos:earned.logros,nivelesNuevos:earned.niveles,personalizada:false,margen3:match.margen3===true,precisionMax:Math.max(0,...(match.precisiones||[]))},[`movimientos/${id}/${op}`]:{tipo:'partida',delta:earned.monedas,saldo,fecha:db.serverTimestamp(),partida:match.id}};
 }
 async function purchase(id,itemId,op='compra-'+crypto.randomUUID()){const item=catalog.find(i=>i.id===itemId),saldo=await get(id,`users/${id}/monedas`),delta=item.requisito?0:-item.precio;return {[`users/${id}/monedas`]:saldo+delta,[`users/${id}/ultimaOperacion`]:op,[`users/${id}/inventario/${itemId}`]:true,[`movimientos/${id}/${op}`]:{tipo:item.requisito?'desbloqueo':'compra',itemId,delta,saldo:saldo+delta,fecha:db.serverTimestamp()}};}
 try{
  await env.clearDatabase();await seed({catalogo:Object.fromEntries(catalog.map(i=>[i.id,i]))});await assertSucceeds(create('ana','Ana5','ANA235'));await assertSucceeds(create('bob','Bob5','BOB235'));await assertSucceeds(create('cara','Cara5','CAR235'));
  await assertFails(create('fake','Falso5','FAL235',{monedas:100}));await assertFails(set('ana','catalogo/hierro/precio',1));await assertFails(set('ana','users/ana/monedas',500));await assertFails(set('ana','users/ana/inventario/hierro',true));
  const match={id:'uno',modo:'solo',dificultad:'normal',pasillos:1,precisiones:[.9],encuentros:[{id:38,ok:true}],tiempoMs:1000,racha:1};const first=await reward('ana',match);await assertSucceeds(patch('ana',first));assert.equal(await get('ana','users/ana/monedas'),43);assert.equal((await get('ana','users/ana/estadisticas')).bestiario[38].vencidos,1);
  await assertFails(patch('ana',first));await assertFails(set('ana','movimientos/ana/partida-uno/delta',999));await assertFails(set('ana','users/ana/estadisticas/logros',null));await assertFails(set('ana','users/ana/estadisticas/logros/0','precision'));await assertFails(set('ana','users/ana/estadisticas/logros/2','veterano'));note('Recibo atómico, 43 almas exactas, monstruo 38, idempotencia y retención de logros.');
  for(const [name,change]of [['sin-movimiento',v=>delete v['movimientos/ana/partida-dos']],['sin-recibo',v=>delete v['partidas/ana/dos']],['personalizada',v=>v['partidas/ana/dos'].personalizada=true],['formula',v=>v['partidas/ana/dos'].baseMonedas++],['logro-falso',v=>v['users/ana/estadisticas'].logros.push('pesadilla10')],['nivel-falso',v=>v['partidas/ana/dos'].nivelesNuevos++],['tope',v=>{v['partidas/ana/dos'].monedas=1001;v['users/ana/monedas']=1044;v['movimientos/ana/partida-dos'].delta=1001;v['movimientos/ana/partida-dos'].saldo=1044;}]]){const value=await reward('ana',{...match,id:'dos'});change(value);await assertFails(patch('ana',value));}
  const solo=await reward('ana',{...match,id:'tope-real',dificultad:'pesadilla',pasillos:1000,racha:1000});await assertSucceeds(patch('ana',solo));assert.equal((await get('ana','partidas/ana/tope-real')).monedas,1000);
  await assertSucceeds(patch('bob',await reward('bob',{id:'coop',modo:'coop',dificultad:'facil',pasillos:3})));assert.equal((await get('bob','partidas/bob/coop')).baseMonedas,3);
  await assertSucceeds(patch('cara',await reward('cara',{id:'carrera',modo:'race',dificultad:'normal',puntos:199,puesto:1})));assert.equal((await get('cara','partidas/cara/carrera')).baseMonedas,31);note('SOLO/COOP/CARRERA, redondeo, bonificaciones y máximo 1000; rechazos de recibos falsos/incompletos.');
  await assertFails(patch('bob',await purchase('bob','hierro')));await assertSucceeds(patch('ana',await purchase('ana','hierro','compra-hierro')));assert.equal(await get('ana','users/ana/monedas'),943);assert.equal(await get('ana','users/ana/inventario/hierro'),true);
  await assertFails(patch('ana',await purchase('ana','hierro')));await assertFails(set('ana','users/ana/inventario/hierro',null));await assertFails(set('ana','users/ana/monedas',942));await assertFails(set('ana','movimientos/ana/compra-hierro',null));
  const cheap=await purchase('ana','huesos');cheap[Object.keys(cheap).find(k=>k.startsWith('movimientos/'))].delta=-1;await assertFails(patch('ana',cheap));const extra=await purchase('ana','huesos');extra['users/ana/inventario/raices']=true;await assertFails(patch('ana',extra));
  const noItem=await purchase('ana','huesos');delete noItem['users/ana/inventario/huesos'];await assertFails(patch('ana',noItem));
  await assertFails(set('ana','users/ana/equipado',{marco:'huesos',titulo:'',fondo:''}));await assertSucceeds(set('ana','users/ana/equipado',{marco:'hierro',titulo:'',fondo:''}));await assertFails(set('ana','users/ana/equipado',{marco:'',titulo:'hierro',fondo:''}));await assertSucceeds(set('ana','users/ana/equipado',{marco:'',titulo:'',fondo:''}));note('Compra exacta, saldo insuficiente, compra repetida, inventario/movimiento indivisibles y equipamiento por tipo.');
  await assertFails(patch('bob',await purchase('bob','sangre')));await assertSucceeds(patch('ana',await purchase('ana','sangre')));await seed({'users/ana/xp':Array.from({length:9},(_,i)=>Math.round(80*(i+1)**1.35)).reduce((a,b)=>a+b,0),'users/ana/nivel':10});await assertSucceeds(patch('ana',await purchase('ana','titulo-7')));await assertFails(patch('bob',await purchase('bob','titulo-7')));note('Desbloqueos sin coste por logro Pesadilla 10 y nivel; requisitos pendientes rechazados.');
  await seed({'users/bob/monedas':100});const concurrent=await Promise.all([purchase('bob','hierro','compra-a'),purchase('bob','titulo-1','compra-b')]);const race=await Promise.allSettled(concurrent.map(v=>patch('bob',v)));assert.equal(race.filter(r=>r.status==='fulfilled').length,1);assert.equal(await get('bob','users/bob/monedas'),0);assert.equal(Object.keys(await get('bob','users/bob/inventario')).length,1);note('Dos compras concurrentes con saldo para una: una aceptada, otra rechazada.');
  await assertSucceeds(set('ana','users/ana/ajustes',DEFAULT_SETTINGS));assert.deepEqual(await get('ana','users/ana/ajustes'),DEFAULT_SETTINGS);for(const bad of [{...DEFAULT_SETTINGS,master:2},{...DEFAULT_SETTINGS,fps:120},{...DEFAULT_SETTINGS,otro:true},{...DEFAULT_SETTINGS,keyBook:DEFAULT_SETTINGS.keyCanvas}])await assertFails(set('ana','users/ana/ajustes',bad));await assertFails(set('bob','users/ana/ajustes',DEFAULT_SETTINGS));note('Ajustes completos guardados; rangos, FPS, atajos repetidos, campos extra y escrituras ajenas rechazados.');
  await assertSucceeds(set('ana','users/ana/preferencias/perfil','amigos'));await assertFails(db.get(db.ref(ctx('bob'),'users/ana')));assert.equal(await get('bob','users/ana/nombre'),'Ana5');assert.equal((await get('bob','users/ana/equipado')).marco,'');await seed({'social/bob/confirmados/ana':true,'social/ana/confirmados/bob':true});await assertSucceeds(db.get(db.ref(ctx('bob'),'users/ana')));
  await seed({'presencia/ana':{estado:'menu',fecha:Date.now()}});await assertSucceeds(db.get(db.ref(ctx('bob'),'presencia/ana')));await assertSucceeds(set('ana','users/ana/preferencias/estadoVisible',false));await assertFails(db.get(db.ref(ctx('bob'),'presencia/ana')));await assertFails(set('ana','users/ana/preferencias/perfil','nadie'));note('Perfil privado: solo amigos; identidad pública para marcadores; estado oculto incluso a amigos.');
  const now=Date.now(),meta={host:'bob',modo:'race',estado:'lobby',ronda:0,pasillos:0,vidas:3,inicioFase:0,semilla:123,dificultad:'normal',personalizada:false,createdAt:now,expiresAt:now+100000,uniqueAvatars:false};await seed({'rooms/PRIV':{meta,jugadores:{bob:{nombre:'Bob5',avatar:1,slot:1,rol:'',listo:false,iaLista:true,progreso:100,ausente:false,changed:now}}}});const invitation={de:'bob',nombre:'Bob5',sala:'PRIV',modo:'race',dificultad:'normal',creadoEn:db.serverTimestamp(),caducaEn:Date.now()+119000};await assertSucceeds(patch('bob',{'invitaciones/ana/si':invitation,'enviadas/bob/si':{dest:'ana'}}));await assertSucceeds(set('ana','users/ana/preferencias/invitaciones',false));await assertFails(patch('bob',{'invitaciones/ana/no':{...invitation,creadoEn:db.serverTimestamp()},'enviadas/bob/no':{dest:'ana'}}));note('La misma invitación válida se rechaza al desactivar la recepción.');
  assert.equal((await get('ana','users/ana')).monedas,943);fs.writeFileSync(path.join(root,'PRUEBAS-AMPLIACION5-REGLAS.json'),JSON.stringify({version:'1.4.0',report},null,2)+'\n');
 }finally{await env.cleanup();}
})().catch(e=>{console.error(e);process.exitCode=1;});
