// Navegador con Auth/RTDB reales emulados; CLIP usa un doble controlado.
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {server,setup,state,ink,fonts,shots,errors,primary,runtime,browserOptions,forbiddenServices}=require('./ui.cjs'),{chromium}=require(primary+'/playwright');
const req=require('node:module').createRequire(runtime+'/firebase-admin/package.json'),{initializeApp,deleteApp}=req('firebase-admin/app'),{getDatabase}=req('firebase-admin/database');
const {initializeTestEnvironment}=require(runtime+'/@firebase/rules-unit-testing'),root=path.resolve(__dirname,'..'),monsters=JSON.parse(fs.readFileSync(path.join(root,'monsters.json'))),catalog=JSON.parse(fs.readFileSync(path.join(root,'cosmeticos.json')));
async function settings(page,category){if(!await page.locator('#settings-modal').evaluate(e=>e.open))await page.click('#settings-open');await page.click(`[data-category="${category}"]`);}
async function saved(page){await page.waitForFunction(()=>document.getElementById('settings-status').textContent==='Guardado.');}
async function register(page,name){await page.click('#auth-register');await page.fill('#auth-name',name);await page.fill('#auth-email',name.toLowerCase()+'@example.invalid');await page.fill('#auth-password','Prueba12345');await page.click('#auth-submit');await state(page,'menu');return page.evaluate(async()=>(await import('/js/auth.js?v=1.4.0')).currentUser().uid);}
(async()=>{
 await new Promise(r=>server.listen(8002,'127.0.0.1',r));const browser=await chromium.launch(browserOptions),env=await initializeTestEnvironment({projectId:'demo-pasillo',database:{host:'127.0.0.1',port:9000,rules:fs.readFileSync(path.join(root,'database.rules.json'),'utf8')}});
 const app=initializeApp({projectId:'demo-pasillo',databaseURL:'https://demo-pasillo.firebaseio.com',credential:{getAccessToken:async()=>({access_token:'owner',expires_in:3600})}},'e5-ui'),rt=getDatabase(app),report=[];const note=t=>{report.push(t);console.log('OK:',t);};
 try{
  await env.clearDatabase();await rt.ref('catalogo').set(Object.fromEntries(catalog.map(i=>[i.id,i])));
  const gc=await browser.newContext({viewport:{width:1440,height:1000}}),g=await setup(gc);await g.click('#auth-guest');await state(g,'menu');await settings(g,'cuenta');assert.equal(await g.locator('#settings-content button').count(),2);assert.equal(await g.getByRole('button',{name:'CERRAR SESIÓN',exact:true}).count(),0);await fonts(g);
  await settings(g,'audio');assert.equal(await g.locator('#settings-content input[type=range]').count(),5);await g.locator('#setting-master').fill('0.55');await g.locator('#setting-master').dispatchEvent('change');await saved(g);await g.getByRole('button',{name:'PROBAR SONIDO',exact:true}).click();await g.click('#settings-reset');assert.equal(await g.locator('#setting-master').inputValue(),'0.8');
  await settings(g,'calidad');await g.selectOption('#setting-quality','baja');await g.uncheck('#setting-grain');await g.check('#setting-scanlines');await g.selectOption('#setting-fps','30');assert.equal(await g.locator('body').getAttribute('data-quality'),'baja');assert(await g.locator('body').evaluate(e=>e.classList.contains('effect-scanlines')));await g.click('#settings-reset');assert.equal(await g.locator('#setting-fps').inputValue(),'60');
  await settings(g,'juego');await g.selectOption('#setting-difficulty','facil');await g.selectOption('#setting-defaultBrush','marker');await g.selectOption('#setting-defaultTool','ellipse');await g.fill('#setting-keyBook','x');await g.locator('#setting-keyBook').dispatchEvent('change');await g.fill('#setting-keyCanvas','z');await g.locator('#setting-keyCanvas').dispatchEvent('change');await g.selectOption('#setting-timerSize','grande');
  await settings(g,'accesibilidad');await g.check('#setting-captions');await g.selectOption('#setting-flash','reduced');await g.selectOption('#setting-screamer','attenuated');await g.check('#setting-highContrast');await g.selectOption('#setting-colorblind','protanopia');await g.check('#setting-largeText');await fonts(g);await g.screenshot({path:path.join(shots,'v14-settings-desktop.png'),fullPage:true});await g.click('#settings-reset');await g.check('#setting-captions');
  await settings(g,'datos');assert((await g.locator('#settings-content').textContent()).includes('1.4.0'));await g.getByRole('button',{name:'BORRAR RÉCORDS LOCALES',exact:true}).click();await g.click('#settings-close');await g.reload();await g.click('#accept');await g.click('#auth-guest');await state(g,'menu');assert.equal(await g.evaluate(async()=>(await import('/js/settings.js?v=1.4.0')).getSettings().difficulty),'facil');note('Seis categorías, controles/RESTABLECER, aplicación visual, ajustes locales y F5; Cuenta invitado solo acceso/registro.');
  await g.click('#play');await g.click('#solo-mode');assert.equal(await g.locator('#prep-difficulty').inputValue(),'facil');await g.fill('#prep-seed','indice-38');await g.click('#prep-start');await state(g,'book');assert.equal(await g.locator('#bookmarks button').count(),monsters.length);assert.equal(await g.locator('#bookmarks').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),8);
  await g.locator('#bookmarks button').first().focus();await g.keyboard.press('ArrowRight');assert.equal(await g.evaluate(()=>document.activeElement.dataset.monster),'2');await g.keyboard.press('ArrowDown');assert.equal(await g.evaluate(()=>document.activeElement.dataset.monster),'10');await g.keyboard.press('Enter');assert.equal(await g.locator('#book-name').textContent(),monsters[9].nombre);assert.equal(await g.locator('#book-lore').textContent(),monsters[9].lore);await g.waitForTimeout(450);await g.keyboard.press('Escape');assert(await g.locator('#book').evaluate(e=>e.classList.contains('show-index')));
  const cell=g.locator('#bookmarks button').first();await cell.click({button:'right'});assert(await cell.evaluate(e=>e.classList.contains('discarded')));await g.keyboard.press('z');assert(await g.locator('#draw-view').isVisible());assert.equal(await g.locator('#brush-kind').inputValue(),'marker');assert(await g.locator('[data-tool=ellipse]').evaluate(e=>e.classList.contains('selected')));await g.click('[data-tool=brush]');await ink(g);
  const src=await g.locator('#monster-face').getAttribute('src'),monster=monsters.find(m=>src.includes(m.imagen));await g.evaluate(label=>window.__label=label,monster.debilidades[0].etiquetaCLIP);await g.click('#show');await state(g,'win');await state(g,'book');assert.equal(await g.locator('#bookmarks .discarded').count(),0);await g.click('#pause');await g.click('#pause-settings');assert(await g.locator('#settings-modal').evaluate(e=>e.open));await g.click('#settings-close');assert(await g.locator('#pause-modal').evaluate(e=>e.open));await g.click('#quit');
  await g.setViewportSize({width:390,height:844});await settings(g,'audio');await fonts(g);assert.equal(await g.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await g.screenshot({path:path.join(shots,'v14-settings-mobile.png'),fullPage:true});await g.click('#settings-close');await g.click('#play');await g.click('#solo-mode');await g.fill('#prep-seed','movil');await g.click('#prep-start');await state(g,'book');assert.equal(await g.locator('#bookmarks').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),4);await g.locator('#bookmarks button').first().dispatchEvent('pointerdown',{pointerId:19,pointerType:'touch'});await g.waitForTimeout(600);await g.locator('#bookmarks button').first().dispatchEvent('pointerup',{pointerId:19,pointerType:'touch'});assert.equal(await g.locator('#bookmarks .discarded').count(),1);await fonts(g);await g.screenshot({path:path.join(shots,'v14-index-mobile.png'),fullPage:true});await g.click('#pause');await g.click('#quit');note('Índice 38, escritorio 8/móvil 4 columnas, flechas/Enter/Esc, clic derecho/pulsación larga, reinicio por pasillo y configuración desde pausa.');
  await g.goto('http://127.0.0.1:8002/?debug=1');await g.click('#accept');await g.click('#auth-guest');await g.click('#lab-open');await state(g,'lab');assert.equal(await g.locator('#lab-target option').count(),monsters.length+1);await g.click('#lab-analyze');await g.waitForFunction(()=>document.getElementById('lab-status').textContent==='No dibujaste nada.');assert.equal(await g.locator('.lab-result').count(),0);
  await g.evaluate(label=>{window.__allLabels=true;window.__label=label;},monsters.find(m=>m.id===31).debilidades.find(w=>w.id==='key').etiquetaCLIP);await g.click('[data-tool=brush]');await ink(g);await g.click('#lab-analyze');await g.waitForFunction(()=>document.querySelectorAll('.lab-result').length===5);assert((await g.locator('.lab-result').first().textContent()).includes('llave'));assert.equal(await g.locator('.lab-result').first().locator('img').count(),monsters.filter(m=>m.debilidades.some(w=>w.id==='key')).length);assert.equal((await g.locator('#lab-all').textContent()).split('\n').length,70);await g.selectOption('#lab-target','31');assert((await g.locator('#lab-verdict').textContent()).includes('✓'));await g.selectOption('#lab-target','36');assert((await g.locator('#lab-verdict').textContent()).includes('✗'));
  await g.check('#lab-auto');await g.evaluate(label=>window.__label=label,monsters.find(m=>m.id===36).debilidades[0].etiquetaCLIP);await ink(g);await g.waitForFunction(()=>document.querySelector('.lab-result')?.textContent.includes('jeringa'));await fonts(g);assert.equal(await g.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await g.screenshot({path:path.join(shots,'v14-lab-mobile.png'),fullPage:true});await g.click('#lab-back');await state(g,'menu');assert.equal(Object.keys((await rt.ref('users').get()).val()||{}).length,0);assert(!(await rt.ref('partidas').get()).exists());assert(!(await rt.ref('movimientos').get()).exists());note('Laboratorio invitado: lienzo compartido, vacío, top 5 español/barras/miniaturas, auto 1 s, objetivo ✓/✗ y 70 etiquetas debug; sin progreso.');await gc.close();
  const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await setup(c),uid=await register(p,'Cuenta5');await settings(p,'audio');await p.locator('#setting-master').fill('0.42');await p.locator('#setting-master').dispatchEvent('change');await saved(p);assert.equal((await rt.ref(`users/${uid}/ajustes`).get()).val().master,.42);await settings(p,'cuenta');assert((await p.locator('#settings-content').textContent()).includes('🔒 Cuenta5'));assert(!(await p.locator('#settings-content').textContent()).includes('cuenta5@example.invalid'));assert.equal(await p.getByRole('button',{name:'CERRAR SESIÓN',exact:true}).count(),1);await p.click('#settings-close');assert.equal(await p.getByRole('button',{name:'CERRAR SESIÓN',exact:true}).count(),0);assert.equal(await p.locator('#profile #password-form,#profile #delete-account,#menu #password-form,#menu #delete-account').count(),0);
  const twinContext=await browser.newContext({viewport:{width:1200,height:900}}),twin=await setup(twinContext);await twin.fill('#auth-email','cuenta5@example.invalid');await twin.fill('#auth-password','Prueba12345');await twin.click('#auth-submit');await state(twin,'menu');await settings(twin,'audio');assert.equal(await twin.locator('#setting-master').inputValue(),'0.42');await twin.locator('#setting-ambient').fill('0.25');await twin.locator('#setting-ambient').dispatchEvent('change');await saved(twin);await p.waitForFunction(async()=>(await import('/js/settings.js?v=1.4.0')).getSettings().ambient===.25);await twinContext.close();note('Cuenta: identidad de solo lectura/correo oculto, operaciones solo Configuración > Cuenta y sincronización de ajustes entre dispositivos.');
  const award=await p.evaluate(async()=>{const {awardMatch}=await import('/js/xp.js?v=1.4.0');const match={id:'tienda-test',modo:'solo',dificultad:'normal',pasillos:300,encuentros:[{id:38,ok:true}],precisiones:[.9],racha:300,tiempoMs:1000};const [a,b]=await Promise.all([awardMatch(match),awardMatch(match)]);return {a,b};});assert.equal((await rt.ref(`movimientos/${uid}`).get()).numChildren(),1);assert.equal((await rt.ref(`users/${uid}/monedas`).get()).val(),1000);assert.equal(award.a.monedas,1000);assert.equal(award.b.monedas,1000);
  const noRewards=await p.evaluate(async()=>{const {awardMatch}=await import('/js/xp.js?v=1.4.0');return awardMatch({id:'custom-lab',modo:'solo',dificultad:'normal',pasillos:300,personalizada:true});});assert.equal(noRewards.monedas,0);assert(!(await rt.ref(`partidas/${uid}/custom-lab`).get()).exists());
  await p.click('#shop-open');await state(p,'shop');assert.equal(await p.locator('.shop-item').count(),8);await p.locator('[data-item=dientes] button').click();await p.waitForFunction(()=>document.getElementById('shop-status').textContent.includes('insuficientes'));const buy=async(type,id)=>{await p.click(`#shop-tabs [data-type=${type}]`);const button=p.locator(`[data-item="${id}"] button`);await button.click();await p.waitForFunction(id=>document.querySelector(`[data-item="${id}"] button`)?.textContent==='EQUIPAR',id);await p.locator(`[data-item="${id}"] button`).click();await p.waitForFunction(id=>document.querySelector(`[data-item="${id}"] button`)?.textContent==='DESEQUIPAR',id);};await buy('marco','hierro');await buy('titulo','titulo-1');await buy('fondo','hospital-perfil');assert.equal((await rt.ref(`users/${uid}/monedas`).get()).val(),700);assert.equal(await p.locator('#shop-preview .cosmetic-frame').count(),1);assert((await p.locator('#shop-preview .cosmetic-title').textContent()).includes('Superviviente'));const repeat=await p.evaluate(async()=>{try{await (await import('/js/economy.js?v=1.4.0')).acquireItem('hierro');return 'error';}catch(e){return e.message;}});assert.equal(repeat,'Ya lo tienes.');await fonts(p);await p.screenshot({path:path.join(shots,'v14-shop-desktop.png'),fullPage:true});await p.click('#shop-back');assert.equal(await p.locator('#menu-profile .cosmetic-frame').count(),1);
  await p.click('#profile-open');await p.waitForFunction(()=>document.getElementById('corridor').dataset.loaded==='true'&&document.getElementById('corridor').dataset.environment.startsWith('profile:'));const background=await p.locator('#corridor').getAttribute('style');assert(background.includes('hospital-perfil'));await p.evaluate(()=>{window.__customBackground=document.getElementById('corridor');document.dispatchEvent(new Event('visibilitychange'));});await p.setViewportSize({width:1280,height:900});assert.equal(await p.locator('#corridor').evaluate(e=>e===window.__customBackground),true);await p.screenshot({path:path.join(shots,'v14-profile-desktop.png'),fullPage:true});await p.click('#profile-back');await p.evaluate(async()=>{await (await import('/js/records.js?v=1.4.0')).publishRecord({puntuacion:7});});
  const oc=await browser.newContext({viewport:{width:1280,height:900}}),other=await setup(oc),otherUid=await register(other,'Visita5');await other.click('[data-dialog=records]');await other.waitForFunction(()=>document.querySelector('#global-list .cosmetic-frame'));assert((await other.locator('#global-list .cosmetic-title').textContent()).includes('Superviviente'));await other.locator('#global-list .player-identity').click();await state(other,'profile');await other.waitForFunction(()=>document.getElementById('corridor').dataset.environment.startsWith('profile:'));assert((await other.locator('#corridor').getAttribute('style')).includes('hospital-perfil'));assert.equal(await other.locator('#avatar-editor').isHidden(),true);await other.click('#profile-back');
  await p.click('#play');await p.click('#race-mode');await p.click('#create-room');await p.click('#prep-start');await state(p,'lobby');assert.equal(await p.locator('#players .cosmetic-frame').count(),1);assert((await p.locator('#players .cosmetic-title').textContent()).includes('Superviviente'));await p.click('#leave-room');note('Recompensa concurrente una sola vez, custom 0; tienda/saldo/compra repetida; marco/título en menú, lobby y ranking; fondo propio y de otro perfil persistente.');
  await settings(p,'cuenta');await p.selectOption('#setting-perfil','amigos');await saved(p);await p.uncheck('#setting-estadoVisible');await saved(p);await p.uncheck('#setting-invitaciones');await saved(p);assert.equal((await rt.ref(`users/${uid}/preferencias`).get()).val().invitaciones,false);const privateProfile=await other.evaluate(async uid=>{try{await (await import('/js/profile.js?v=1.4.0')).readProfile(uid);return 'error';}catch(e){return e.message;}},uid);assert.equal(privateProfile,'Perfil privado.');await p.fill('#current-password','Prueba12345');await p.fill('#new-password','Nueva12345');await p.click('#password-form button');await p.waitForFunction(()=>document.getElementById('settings-status').textContent.includes('cambiada'));await p.fill('#delete-name','Incorrecto');await p.fill('#delete-password','Nueva12345');await p.click('#delete-account');assert.equal(await p.locator('#settings-status').textContent(),'El nombre no coincide.');await p.fill('#delete-name','Cuenta5');await p.click('#delete-account');await state(p,'access');assert(!(await rt.ref(`users/${uid}`).get()).exists());assert(!(await rt.ref(`movimientos/${uid}`).get()).exists());assert(!(await rt.ref(`records_solo_normal/${uid}`).get()).exists());note('Privacidad de perfil/estado/invitaciones; contraseña actual, confirmación por nombre y eliminación con movimientos/récord.');
  assert.deepEqual(errors,[]);assert.deepEqual(forbiddenServices,[]);const result={version:'1.4.0',report,pageErrors:errors,forbiddenServices,CLIP:'Doble controlado; calidad de inferencia real pendiente de prueba manual.'};fs.writeFileSync(path.join(root,'PRUEBAS-AMPLIACION5-UI.json'),JSON.stringify(result,null,2)+'\n');await c.close();await oc.close();
 }finally{await browser.close();server.close();await deleteApp(app);await env.cleanup();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
