// Casos de cierre: herramienta Admin local, audio tardío, JSON y cosméticos refrescados.
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{spawnSync}=require('node:child_process');
const {server,setup,state,ink,fonts,shots,errors,primary,runtime,browserOptions,forbiddenServices}=require('./ui.cjs'),{chromium}=require(primary+'/playwright');
const req=require('node:module').createRequire(runtime+'/firebase-admin/package.json'),{initializeApp,deleteApp}=req('firebase-admin/app'),{getDatabase}=req('firebase-admin/database'),{initializeTestEnvironment}=require(runtime+'/@firebase/rules-unit-testing');
const root=path.resolve(__dirname,'..'),monsters=JSON.parse(fs.readFileSync(path.join(root,'monsters.json')));
const register=async(p,name)=>{await p.click('#auth-register');await p.fill('#auth-name',name);await p.fill('#auth-email',name.toLowerCase()+'@example.invalid');await p.fill('#auth-password','Prueba12345');await p.click('#auth-submit');await state(p,'menu');return p.evaluate(async()=>(await import('/js/auth.js?v=1.4.0')).currentUser().uid);};
(async()=>{
 await new Promise(r=>server.listen(8002,'127.0.0.1',r));const browser=await chromium.launch(browserOptions),env=await initializeTestEnvironment({projectId:'demo-pasillo',database:{host:'127.0.0.1',port:9000,rules:fs.readFileSync(path.join(root,'database.rules.json'),'utf8')}}),app=initializeApp({projectId:'demo-pasillo',databaseURL:'https://demo-pasillo.firebaseio.com',credential:{getAccessToken:async()=>({access_token:'owner',expires_in:3600})}},'e5-extra'),rt=getDatabase(app),report=[],note=t=>{report.push(t);console.log('OK:',t);};
 try{
  await env.clearDatabase();const catalogArgs=['tools/load-catalog.mjs','--project','demo-pasillo','--database','https://demo-pasillo.firebaseio.com'],opts={cwd:root,env:{...process.env,PASILLO_TEST_MODULES:runtime,GOOGLE_CLOUD_PROJECT:'demo-pasillo'},encoding:'utf8',timeout:20000};const preview=spawnSync(process.execPath,catalogArgs,opts);assert.equal(preview.status,0,preview.stderr);assert(preview.stdout.includes('Vista previa'));assert(!(await rt.ref('catalogo').get()).exists());const applied=spawnSync(process.execPath,[...catalogArgs,'--apply'],opts);assert.equal(applied.status,0,applied.stderr);assert.equal((await rt.ref('catalogo').get()).numChildren(),28);assert(!(await rt.ref('users').get()).exists());note('Herramienta de catálogo real: vista previa sin escribir; --apply carga 28 en RTDB emulado sin tocar usuarios.');
  const c=await browser.newContext({viewport:{width:1280,height:1000},permissions:['clipboard-read','clipboard-write']}),p=await setup(c);await p.click('#auth-guest');await state(p,'menu');
  const sound=await p.evaluate(async m=>{const {Atmosphere}=await import('/js/audio.js?v=1.4.0'),{setSettings,getSettings}=await import('/js/settings.js?v=1.4.0');setSettings({captions:true});window.__haptics=[];Object.defineProperty(navigator,'vibrate',{configurable:true,value:pattern=>{window.__haptics.push(pattern);return true;}});const a=new Atmosphere({...getSettings(),master:.5,music:.1,effects:.2,screamVolume:.3,ambient:.4});await a.start();const absent=!a.ambientSource;await a.preload([m]);a.monster('appear',m);const caption=document.getElementById('sound-caption').textContent;a.monster('scream',m);a.effect('heart');await new Promise(r=>setTimeout(r,350));const result={absent,loop:!!a.ambientSource,independent:a.fx!==a.screamBus&&a.ambientBus!==a.music,gains:[a.master,a.music,a.fx,a.screamBus,a.ambientBus].map(g=>g.gain.value),caption,heart:document.getElementById('sound-caption').textContent,haptics:window.__haptics};await a.ctx.close();return result;},monsters[0]);assert(sound.absent&&sound.loop&&sound.independent);sound.gains.forEach((v,i)=>assert(Math.abs(v-[.5,.1,.2,.3,.4][i])<.03));assert.equal(sound.caption,'Aparición');assert.equal(sound.heart,'Latido');assert(sound.haptics.includes(25)&&sound.haptics.includes(80));note('Cinco buses y ganancias independientes; ambience descargado después de iniciar; subtítulos e integración de vibración.');
  await p.goto('http://127.0.0.1:8002/?debug=1');await p.click('#accept');await p.click('#auth-guest');await p.click('#lab-open');await p.evaluate(label=>{window.__allLabels=true;window.__label=label;},monsters.at(-1).debilidades[0].etiquetaCLIP);await ink(p);await p.click('#lab-analyze');await p.waitForFunction(()=>document.querySelectorAll('.lab-result').length===5);await p.locator('#lab-debug').evaluate(e=>e.open=true);await p.click('#lab-copy');assert.equal(await p.locator('#lab-status').textContent(),'Copiado.');const json=JSON.parse(await p.evaluate(()=>navigator.clipboard.readText()));assert.equal(json.results.length,70);assert.equal(json.results[0].nombre,'reloj de arena');assert(json.ms>0&&json.confusables.includes('glass_jar'));assert.equal(await p.locator('#debug').isHidden(),true);
  // Una navegación ajena al botón del laboratorio debe devolver el lienzo a su lugar.
  await p.evaluate(()=>document.getElementById('account-open').click());await state(p,'access');assert.equal(await p.locator('#lab-dock #draw-view').count(),0);assert.equal(await p.locator('#workbench #draw-view').count(),1);await p.click('#auth-guest');await p.click('#play');await p.click('#solo-mode');await p.fill('#prep-seed','retorno-lab');await p.click('#prep-start');await state(p,'book');await ink(p);await p.click('#pause');await p.click('#quit');note('COPIAR RESULTADOS entrega 70 candidatas españolas/tiempo/confusables; al salir por otra ruta el lienzo vuelve a la partida.');
  // Perfil con WebP bloqueado: el PNG conserva el mismo nodo de fondo.
  const pc=await browser.newContext({viewport:{width:1280,height:1000}});await pc.route('**/assets/ui/fondos/*.webp*',r=>r.abort());const owner=await setup(pc),uid=await register(owner,'CosmA5');await rt.ref(`users/${uid}/inventario`).set({hierro:true,huesos:true,'titulo-1':true,'hospital-perfil':true});await owner.evaluate(async()=>{const {equipItem}=await import('/js/economy.js?v=1.4.0');await equipItem('hierro','marco');await equipItem('titulo-1','titulo');await equipItem('hospital-perfil','fondo');});await owner.click('#profile-open');await owner.waitForFunction(()=>document.getElementById('corridor').dataset.loaded==='true'&&document.getElementById('corridor').style.backgroundImage.includes('hospital-perfil.png'));await fonts(owner);await owner.click('#profile-back');await owner.evaluate(async()=>{await (await import('/js/records.js?v=1.4.0')).publishRecord({puntuacion:7});});
  const qc=await browser.newContext({viewport:{width:390,height:844}}),q=await setup(qc);await register(q,'CosmB5');await q.click('[data-dialog=records]');await q.waitForFunction(()=>document.querySelector('#global-list .cosmetic-frame')?.alt==='Hierro Oxidado');await q.click('#close-modal');await owner.evaluate(async()=>{await (await import('/js/economy.js?v=1.4.0')).equipItem('huesos','marco');});await q.click('[data-dialog=records]');await q.waitForFunction(()=>document.querySelector('#global-list .cosmetic-frame')?.alt==='Huesos');await fonts(q);await q.click('#close-modal');await q.click('#shop-open');assert.equal(await q.locator('.shop-item').count(),8);assert.equal(await q.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await fonts(q);await q.screenshot({path:path.join(shots,'v14-shop-mobile.png'),fullPage:true});note('PNG de perfil cuando falla WebP, cosméticos actualizados al reabrir ranking y tienda móvil sin desbordamiento.');
  assert.deepEqual(errors,[]);assert.deepEqual(forbiddenServices,[]);fs.writeFileSync(path.join(root,'PRUEBAS-AMPLIACION5-EXTRAS.json'),JSON.stringify({version:'1.4.0',report,pageErrors:errors,forbiddenServices},null,2)+'\n');await c.close();await pc.close();await qc.close();
 }finally{await browser.close();server.close();await deleteApp(app);await env.cleanup();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
