const assert=require('node:assert/strict'),{spawnSync}=require('node:child_process'),path=require('node:path');
const root=path.resolve(__dirname,'..'),runtime=process.env.PASILLO_TEST_MODULES||(require('node:fs').existsSync(path.join(root,'node_modules/firebase-admin'))?path.join(root,'node_modules'):path.resolve(root,'../qa-runtime/node_modules')),req=require('node:module').createRequire(runtime+'/firebase-admin/package.json');const {initializeApp,applicationDefault,deleteApp}=req('firebase-admin/app'),{getFirestore,Timestamp}=req('firebase-admin/firestore'),{getAuth}=req('firebase-admin/auth'),{getDatabase}=req('firebase-admin/database');
(async()=>{
const app=initializeApp({projectId:'demo-pasillo',databaseURL:'https://demo-pasillo.firebaseio.com',credential:applicationDefault()}),rt=getDatabase(app),fs=getFirestore(app),auth=getAuth(app);
try{
 for(const [uid,name,code]of [['migana','MigAna','MIG234'],['migbob','MigBob','MIG235'],['migcara','MigCara','MIG236']]){
  await auth.createUser({uid,email:uid+'@example.invalid',password:'Prueba12345'});await fs.doc('users/'+uid).set({nombre:name,nombreLower:name.toLowerCase(),codigoAmigo:code,avatar:1,xp:80,nivel:2,creadoEn:Timestamp.fromMillis(1000),ultimaPartida:'anterior',estadisticas:{partidas:1,pasillos:2,mejores:{solo_normal:2},precisionTotal:900,precisionMuestras:1,tiempoMs:3000,rachaMax:2,carrerasGanadas:0,cooperativas:0,bestiario:{},logros:['primera']},preferencias:{solicitudes:true}});await fs.doc(`users/${uid}/partidas/anterior`).set({xp:80,fecha:Timestamp.fromMillis(1200),modo:'solo',dificultad:'normal'});
 }
 await auth.createUser({uid:'migdeleted',email:'migdeleted@example.invalid',password:'Prueba12345'});await fs.doc('users/migdeleted').set({nombre:'Eliminado',codigoAmigo:'DEL234',xp:0});await rt.ref('deletedAccounts/migdeleted').set(true);
 await fs.doc('users/migana/amigos/migbob').set({estado:'amigos',fecha:Timestamp.fromMillis(1500)});await fs.doc('users/migbob/amigos/migana').set({estado:'amigos',fecha:Timestamp.fromMillis(1500)});
 await fs.doc('records_solo_normal/migana').set({uid:'migana',nombre:'MigAna',avatar:1,nivel:2,puntuacion:2,fecha:Timestamp.fromMillis(2000),dificultad:'normal'});await fs.doc('records_coop_normal/hashPrevio').set({uid:'migana',nombre:'MigAna',avatar:1,nivel:2,puntuacion:3,fecha:Timestamp.fromMillis(2500),dificultad:'normal',miembros:['migana','migbob','migcara']});
 const cmd=extra=>{const result=spawnSync(process.execPath,['tools/migrate-spark.mjs','--project','demo-pasillo','--database','https://demo-pasillo.firebaseio.com',...extra],{cwd:root,env:{...process.env,PASILLO_TEST_MODULES:runtime},encoding:'utf8',timeout:45000});console.log(result.stdout,result.stderr);assert.equal(result.status,0);return result;};
 cmd([]);assert.equal((await rt.ref('users').get()).exists(),false);cmd(['--apply']);assert.equal((await rt.ref('users/migana/xp').get()).val(),80);assert.equal((await rt.ref('users/migdeleted').get()).exists(),false);assert.equal((await rt.ref('social/migana/confirmados/migbob').get()).val(),true);assert.equal((await rt.ref('records_coop_normal/migana|migbob|migcara/puntuacion').get()).val(),3);assert.equal((await rt.ref('partidas/migana/anterior/fecha').get()).val(),1200);cmd(['--apply']);assert((await fs.doc('users/migana').get()).exists);assert((await auth.getUser('migana')).uid==='migana');console.log('OK CLI migración: vista previa sin escrituras, copia completa, repetición idempotente y origen/Auth intactos.');
}finally{await deleteApp(app);}
})().catch(error=>{console.error(error);process.exitCode=1;});
