// La economía se valida con snapshots futuros de RTDB: nunca necesita Functions.
import {ECONOMY} from '../js/config.js';
import {SETTINGS_SCHEMA} from '../js/settings-schema.js';
import {account,signed} from './account_rules.mjs';
const integer=(s,min=0,max=1e12)=>`${s}.isNumber() && ${s}.val() % 1 == 0 && ${s}.val() >= ${min} && ${s}.val() <= ${max}`;
const forbid={'.validate':false},own=`${account} && auth.uid == $uid`;
const countLogros=s=>`(${Array.from({length:13},(_,i)=>`(${s}.child('estadisticas/logros/${i}').exists() ? 1 : 0)`).join(' + ')})`;
export function expansionRules(rules,monsters,catalog){
 const u=rules.users.$uid,profile="newData.parent()",future="newData.parent().parent()",op="newData.child('ultimaOperacion').val()",movement=`${future}.child('movimientos').child($uid).child(${op})`;
 u['.read']=`${account} && (auth.uid == $uid || data.child('preferencias/perfil').val() != 'amigos' || root.child('social').child(auth.uid).child('confirmados').child($uid).val() == true)`;
 for(const field of ['nombre','avatar','nivel','equipado']){u[field]||={};u[field]['.read']=account;}
 u.preferencias.estadoVisible={'.read':account,'.validate':'newData.isBoolean()'};u.preferencias.invitaciones={'.read':account,'.validate':'newData.isBoolean()'};u.preferencias.solicitudes['.read']=account;u.preferencias.perfil={'.validate':"newData.val() == 'todos' || newData.val() == 'amigos'"};
 const retained=catalog.map(item=>`(!data.child('inventario/${item.id}').exists() || newData.child('inventario/${item.id}').val() == true)`).join(' && ');
 u['.validate']+=` && (!data.exists() ? ((!newData.child('monedas').exists() || newData.child('monedas').val() == 0) && !newData.child('inventario').exists() && (!newData.child('ultimaOperacion').exists() || newData.child('ultimaOperacion').val() == '')) : ((!data.child('monedas').exists() || newData.child('monedas').exists()) && (!data.child('ultimaOperacion').exists() || newData.child('ultimaOperacion').exists()) && ${retained} && (!data.child('estadisticas/logros').exists() || newData.child('estadisticas/logros').exists())))`;
 u['.write']=u['.write'].replace('!newData.exists() &&',"!newData.exists() && !newData.parent().parent().child('movimientos').child($uid).exists() &&");
 const newBalance="newData.val()",oldBalance="(data.exists() ? data.val() : 0)",coinOp="newData.parent().child('ultimaOperacion').val()",coinMove=`newData.parent().parent().parent().child('movimientos').child($uid).child(${coinOp})`;
 u.monedas={'.validate':`${integer('newData')} && (${newBalance} == ${oldBalance} || (${coinMove}.child('fecha').val() == now && !root.child('movimientos').child($uid).child(${coinOp}).exists() && ${newBalance} == ${oldBalance} + ${coinMove}.child('delta').val()))`};
 u.ultimaOperacion={'.validate':`newData.isString() && newData.val().length <= 160 && (newData.val() == (data.exists() ? data.val() : '') || (newData.val().matches(/^[A-Za-z0-9_-]{1,160}$/) && newData.parent().parent().parent().child('movimientos').child($uid).child(newData.val()).child('fecha').val() == now && !root.child('movimientos').child($uid).child(newData.val()).exists()))`};
 u.ajustes={'.validate':`newData.hasChildren(${JSON.stringify(Object.keys(SETTINGS_SCHEMA))})`,$other:forbid};for(const[key,s]of Object.entries(SETTINGS_SCHEMA)){u.ajustes[key]={'.validate':s.tipo==='boolean'?'newData.isBoolean()':s.tipo==='range'?`newData.isNumber() && newData.val() >= ${s.min} && newData.val() <= ${s.max}`:s.tipo==='key'?"newData.isString() && newData.val().matches(/^[a-z0-9]$/)":s.opciones.map(v=>`newData.val() == ${JSON.stringify(v)}`).join(' || ')};}
 const keys=Object.keys(SETTINGS_SCHEMA).filter(k=>SETTINGS_SCHEMA[k].tipo==='key');for(let i=0;i<keys.length;i++)for(let j=i+1;j<keys.length;j++)u.ajustes['.validate']+=` && newData.child('${keys[i]}').val() != newData.child('${keys[j]}').val()`;
 const cat="root.child('catalogo').child($id)",invMove="newData.parent().parent().parent().parent().child('movimientos').child($uid).child(newData.parent().parent().child('ultimaOperacion').val())";
 u.inventario={$id:{'.validate':`newData.val() == true && ${cat}.exists() && (data.val() == true || (${invMove}.child('itemId').val() == $id && ${invMove}.child('fecha').val() == now && !root.child('movimientos').child($uid).child(newData.parent().parent().child('ultimaOperacion').val()).exists()))`}};
 u.equipado['.validate']="newData.hasChildren(['marco','titulo','fondo'])";u.equipado.$tipo={'.validate':"($tipo == 'marco' || $tipo == 'titulo' || $tipo == 'fondo') && newData.isString() && (newData.val() == '' || (newData.parent().parent().child('inventario').child(newData.val()).val() == true && root.child('catalogo').child(newData.val()).child('tipo').val() == $tipo))"};
 const idPattern=monsters.map(m=>m.id).join('|');u.estadisticas.bestiario.$id['.validate']=`$id.matches(/^(${idPattern})$/) && newData.hasChildren(['vistos','vencidos']) && newData.child('vencidos').val() <= newData.child('vistos').val()`;
 const logros=['primera','diez','cincuenta','carrera','margen','treinta','vistos','racha','coop','precision','pesadilla','veterano','pesadilla10'];u.estadisticas.logros.$i['.validate']=`$i.matches(/^([0-9]|1[0-2])$/) && newData.isString() && newData.val().matches(/^(${logros.join('|')})$/)`;
 // Evita insertar logros arbitrarios o duplicados fuera de una partida.
 const stats="newData.parent().parent()",statsProfile="newData.parent().parent().parent()",newReceipt=`newData.parent().parent().parent().parent().parent().child('partidas').child($uid).child(${statsProfile}.child('ultimaPartida').val())`;
 const oldAchievement=id=>Array.from({length:13},(_,i)=>`root.child('users').child($uid).child('estadisticas/logros/${i}').val() == ${id}`).join(' || ');
 const achievementsTest={primera:`${stats}.child('pasillos').val() >= 1`,diez:`${stats}.child('pasillos').val() >= 10`,cincuenta:`${stats}.child('pasillos').val() >= 50`,carrera:`${stats}.child('carrerasGanadas').val() >= 1`,margen:`${newReceipt}.child('margen3').val() == true`,treinta:monsters.map(m=>`${stats}.child('bestiario/${m.id}/vencidos').val() >= 1`).join(' && '),vistos:monsters.map(m=>`${stats}.child('bestiario/${m.id}/vistos').val() >= 1`).join(' && '),racha:`${stats}.child('rachaMax').val() >= 5`,coop:`${stats}.child('cooperativas').val() >= 1`,precision:`${newReceipt}.child('precisionMax').val() >= 0.9`,pesadilla:`${newReceipt}.child('dificultad').val() == 'pesadilla' && ${newReceipt}.child('pasillos').val() >= 1`,veterano:`${stats}.child('partidas').val() >= 20`,pesadilla10:`${newReceipt}.child('dificultad').val() == 'pesadilla' && ${newReceipt}.child('pasillos').val() >= 10`};
 u.estadisticas.logros.$i['.validate']+=` && ((${oldAchievement('newData.val()')}) || (${newReceipt}.child('fecha').val() == now && (${Object.entries(achievementsTest).map(([id,test])=>`(newData.val() == '${id}' && (${test}))`).join(' || ')})))`;
 u.estadisticas.logros['.validate']=Array.from({length:13},(_,i)=>`(!data.child('${i}').exists() || newData.child('${i}').val() == data.child('${i}').val())`).join(' && ');
 const logrRoot="newData.parent()";u.estadisticas.logros.$i['.validate']+=` && ${Array.from({length:13},(_,i)=>`($i == '${i}' || ${logrRoot}.child('${i}').val() != newData.val())`).join(' && ')}`;
 rules.catalogo={'.read':true,'.write':false};
 const mroot="newData.parent().parent().parent()",mp=`${mroot}.child('users').child($uid)`,oldP="root.child('users').child($uid)",oldCoins=`(${oldP}.child('monedas').exists() ? ${oldP}.child('monedas').val() : 0)`,item="root.child('catalogo').child(newData.child('itemId').val())",req=`${item}.child('requisito')`,eligible=`((${req}.child('tipo').val() == 'nivel' && ${oldP}.child('nivel').val() >= ${req}.child('valor').val()) || (${req}.child('tipo').val() == 'logro' && (${Array.from({length:13},(_,i)=>`${oldP}.child('estadisticas/logros/${i}').val() == ${req}.child('valor').val()`).join(' || ')})))`,rec=`${mroot}.child('partidas').child($uid).child(newData.child('partida').val())`;
 const ledgerShape="newData.hasChildren(['tipo','delta','saldo','fecha'])";
 const ledgerProof=`${mp}.child('ultimaOperacion').val() == $op && ${mp}.child('monedas').val() == newData.child('saldo').val() && newData.child('saldo').val() == ${oldCoins} + newData.child('delta').val()`;
 const purchase=`(newData.child('tipo').val() == 'compra' || newData.child('tipo').val() == 'desbloqueo') && ${item}.exists() && !${oldP}.child('inventario').child(newData.child('itemId').val()).exists() && ${mp}.child('inventario').child(newData.child('itemId').val()).val() == true && (newData.child('tipo').val() == 'compra' ? (!${req}.exists() && ${item}.child('precio').val() > 0 && newData.child('delta').val() == -${item}.child('precio').val()) : (${req}.exists() && ${eligible} && newData.child('delta').val() == 0))`;
 const reward=`newData.child('tipo').val() == 'partida' && $op == 'partida-' + newData.child('partida').val() && ${mp}.child('ultimaPartida').val() == newData.child('partida').val() && !root.child('partidas').child($uid).child(newData.child('partida').val()).exists() && ${rec}.child('fecha').val() == now && newData.child('delta').val() == ${rec}.child('monedas').val()`;
 rules.movimientos={$uid:{'.read':own,'.write':`${own} && root.child('accountCleanup').child($uid).exists() && !newData.exists()`,$op:{'.write':`${signed} && auth.uid == $uid && !data.exists() && newData.exists()`,'.validate':`${ledgerShape} && $op.matches(/^[A-Za-z0-9_-]{1,160}$/) && ${ledgerProof} && ((${purchase}) || (${reward}))`,tipo:{'.validate':"newData.val() == 'partida' || newData.val() == 'compra' || newData.val() == 'desbloqueo'"},delta:{'.validate':integer('newData',-100000,ECONOMY.maxPartida)},saldo:{'.validate':integer('newData')},fecha:{'.validate':'newData.val() == now'},itemId:{'.validate':'newData.isString()'},partida:{'.validate':'newData.isString()'},$other:forbid}}};
 const receipt=rules.partidas.$uid.$id,pr="newData.parent().parent().parent().child('users').child($uid)",mult="(newData.child('dificultad').val() == 'facil' ? 0.5 : newData.child('dificultad').val() == 'dificil' ? 1.5 : newData.child('dificultad').val() == 'pesadilla' ? 2 : 1)",place=`(newData.child('puesto').val() == 1 ? ${ECONOMY.puestos[0]} : newData.child('puesto').val() == 2 ? ${ECONOMY.puestos[1]} : newData.child('puesto').val() == 3 ? ${ECONOMY.puestos[2]} : 0)`,raceBase=`(newData.child('puntos').val() / ${ECONOMY.puntosCarrera} - (newData.child('puntos').val() / ${ECONOMY.puntosCarrera}) % 1 + ${place})`,raw=`(newData.child('modo').val() == 'race' ? ${raceBase} : newData.child('pasillos').val() * (newData.child('modo').val() == 'coop' ? ${ECONOMY.coop} : ${ECONOMY.solo}) * ${mult})`,base=`(${raw} > ${ECONOMY.maxPartida} ? ${ECONOMY.maxPartida} : ${raw} - ${raw} % 1)`,sum=`(newData.child('baseMonedas').val() + newData.child('logrosNuevos').val() * ${ECONOMY.logro} + newData.child('nivelesNuevos').val() * ${ECONOMY.nivel})`;
 receipt['.validate']+=` && (!newData.child('monedas').exists() || (newData.hasChildren(['baseMonedas','pasillos','puntos','puesto','logrosNuevos','nivelesNuevos','personalizada','margen3','precisionMax']) && newData.child('personalizada').val() == false && newData.child('baseMonedas').val() == ${base} && newData.child('logrosNuevos').val() == ${countLogros(pr)} - ${countLogros(oldP)} && newData.child('nivelesNuevos').val() == ${pr}.child('nivel').val() - ${oldP}.child('nivel').val() && newData.child('monedas').val() == (${sum} > ${ECONOMY.maxPartida} ? ${ECONOMY.maxPartida} : ${sum}) && ${pr}.child('ultimaOperacion').val() == 'partida-' + $id && newData.parent().parent().parent().child('movimientos').child($uid).child('partida-' + $id).child('delta').val() == newData.child('monedas').val()))`;
 for(const [key,min,max]of [['monedas',0,ECONOMY.maxPartida],['baseMonedas',0,ECONOMY.maxPartida],['pasillos',0,10000],['puntos',0,50000],['puesto',1,99],['logrosNuevos',0,13],['nivelesNuevos',0,98]])receipt[key]={'.validate':integer('newData',min,max)};receipt.personalizada={'.validate':'newData.val() == false'};receipt.margen3={'.validate':'newData.isBoolean()'};receipt.precisionMax={'.validate':'newData.isNumber() && newData.val() >= 0 && newData.val() <= 1'};
 return rules;
}
