// Datos editoriales; las descripciones de arte están exclusivamente en el manifiesto de producción.
import fs from 'node:fs';
import {COSMETIC_PRICES} from '../js/config.js';
const root=new URL('../',import.meta.url),file=new URL('monsters.json',root);
const all=JSON.parse(fs.readFileSync(file));
const object=(id,nombre,etiquetaCLIP)=>({id,nombre,etiquetaCLIP});
const mirror=all.flatMap(m=>m.debilidades).find(w=>w.id==='mirror');
const flower=all.flatMap(m=>m.debilidades).find(w=>w.id==='flower');
const additions=[
 [31,'El Último Huésped','el-ultimo-huesped','Alquiló una habitación por una noche y nunca entregó el metal que giraba en su cerradura. Cada madrugada prepara la despedida; solo retrocede cuando oye el equipaje cerrarse antes de salir.',[object('key','llave','a metal door key'),object('suitcase','maleta','a travel suitcase with a handle')]],
 [32,'El Abrelatas','el-abrelatas','Quedó encerrado en el almacén durante el invierno. Detesta el giro que aprieta las piezas flojas y todavía busca las raciones selladas que alimentaron a los últimos obreros; al oír abrir una, abandona la persecución.',[object('screwdriver','destornillador','a screwdriver with a handle'),object('tin_can','lata','a sealed cylindrical food tin can')]],
 [33,'El Ombliguero','el-ombliguero','Vivía entre la ropa abandonada del hospicio. Nunca soportó que un pequeño disco atravesara su ojal; las prendas de mangas cortas que cubrían el vientre de los internos lo mantenían encerrado hasta la siguiente colada.',[object('button','botón','a round clothing button with four holes'),object('tshirt','camiseta','a short sleeved t-shirt')]],
 [34,'El Enjambre','el-enjambre','Colonizó el jardín del convento siguiendo el néctar. Los monjes aprendieron a retenerlo bajo un recipiente transparente con tapa; cuando escapaba, un aparato de aspas sobre la mesa dispersaba su avance sin despertar a los demás.',[flower,object('glass_jar','tarro de cristal','a glass storage jar with a screw lid'),object('desk_fan','ventilador','a desk fan with three blades')]],
 [35,'El Ahogado Seco','el-ahogado-seco','Cruzó el desierto buscando un cauce que ya no existía. Solo interrumpe su marcha ante una bebida transparente servida en un recipiente abierto; también sigue a los habitantes que nadan bajo la superficie, aunque nunca consigue alcanzarlos.',[object('glass_water','vaso de agua','an open drinking glass filled with water'),object('fish','pez','a fish with fins and a tail')]],
 [36,'El Parásito','el-parasito','Se instaló en los enfermos del sanatorio y resistió todos los ungüentos. El médico logró desalojarlo al empujar un émbolo, atravesando la piel con una punta hueca.',[object('syringe','jeringa','a medical syringe with a needle and plunger')]],
 [37,'La Máscara de Carne','la-mascara-de-carne','Suplantaba a los actores antes de cada función. Perdía el papel cuando alguien corregía su visión con dos cristales, comprobaba quién lo imitaba al otro lado del azogue o trazaba rojo alrededor de la sonrisa antes de salir a escena.',[object('eyeglasses','gafas','a pair of clear prescription eyeglasses'),mirror,object('lipstick','pintalabios','an open lipstick tube with a red tip')]],
 [38,'El Invertido','el-invertido','Repitió la misma guardia hasta olvidar el amanecer. Solo puede comenzar otra vez cuando alguien gira dos cámaras unidas y deja caer los granos por su cuello estrecho.',[object('hourglass','reloj de arena','an hourglass with sand flowing between two bulbs')]]
];
for(const[id,nombre,slug,lore,debilidades]of additions){const entry={id,nombre,imagen:`assets/monsters/${id}-${slug}.webp`,sonidoAparicion:`assets/audio/appear/${id}.wav`,sonidoScreamer:`assets/audio/scream/${id}.wav`,lore,debilidades};const i=all.findIndex(m=>m.id===id);if(i<0)all.push(entry);else all[i]=entry;}
fs.writeFileSync(file,JSON.stringify(all,null,2)+'\n');
const catalog=[];
const add=(id,tipo,nombre,rareza,archivo='',requisito=null)=>catalog.push({id,tipo,nombre,rareza,precio:requisito?0:COSMETIC_PRICES[rareza],archivo,requisito});
['Hierro Oxidado','Huesos','Raíces','Cadenas','Velas Derretidas','Hilo y Agujas','Dientes','Sangre Seca'].forEach((n,i)=>add(['hierro','huesos','raices','cadenas','velas','hilo','dientes','sangre'][i],'marco',n,['comun','raro','raro','epico','epico','raro','legendario','legendario'][i],`assets/ui/marcos/${['hierro','huesos','raices','cadenas','velas','hilo','dientes','sangre'][i]}.webp`,i===7?{tipo:'logro',valor:'pesadilla10'}:null));
['Superviviente','Cazador de Sombras','Devoralibros','Ojo de Lince','Insomne','Pesadilla Viviente','Veterano','Guardián','Errante','Vigía','Sin Descanso','Último Huésped'].forEach((n,i)=>add(`titulo-${i+1}`,'titulo',n,['comun','raro','raro','epico','raro','legendario','epico','raro','comun','comun','epico','legendario'][i],'',i===5?{tipo:'logro',valor:'pesadilla10'}:i===6?{tipo:'nivel',valor:10}:i===2?{tipo:'logro',valor:'treinta'}:i===11?{tipo:'nivel',valor:20}:null));
['Hospital Abandonado','Mansión','Sótano de Calderas','Iglesia Derruida','Bosque Muerto','Faro Encallado','Biblioteca Quemada','Metro Clausurado'].forEach((n,i)=>add(['hospital-perfil','mansion-perfil','calderas','iglesia','bosque','faro','biblioteca','metro'][i],'fondo',n,['comun','raro','raro','epico','epico','legendario','legendario','epico'][i],`assets/ui/fondos/${['hospital-perfil','mansion-perfil','calderas','iglesia','bosque','faro','biblioteca','metro'][i]}.webp`,i===6?{tipo:'logro',valor:'treinta'}:null));
fs.writeFileSync(new URL('cosmeticos.json',root),JSON.stringify(catalog,null,2)+'\n');
console.log(`${all.length} monstruos; ${catalog.length} cosméticos.`);
