import fs from 'node:fs';
import { validateLore } from './validate_lore.mjs';
const root=new URL('../',import.meta.url),monsters=JSON.parse(fs.readFileSync(new URL('monsters.json',root),'utf8'));
const {errors,counts}=validateLore(monsters);if(errors.length)throw new Error(errors.join('\n'));
fs.writeFileSync(new URL('LORE.md',root),'# Lore de los 30 monstruos\n\nGenerado desde monsters.json. En el libro no se muestran las debilidades.\n\n'+monsters.map((m,i)=>`## ${m.id}. ${m.nombre}\n\n${m.lore}\n\n${counts[i].words} palabras.\n`).join('\n'));
fs.writeFileSync(new URL('AUDIO.md',root),'# Tabla de audio\n\n60 efectos originales de síntesis, propios de cada monstruo: WAV PCM16 mono, 22.050 Hz, sin muestras externas. Aparición: 0,44–0,77 s; screamer: 1,05–1,49 s. Los IDs 23–30 tienen timbres diferenciados de madera, chillidos, voz raspada, vibración líquida, chasquidos, golpes metálicos, aleteo y resonancia acuática.\n\n| ID | Monstruo | Aparición | Screamer |\n|---|---|---|---|\n'+monsters.map(m=>`| ${m.id} | ${m.nombre} | ${m.sonidoAparicion} | ${m.sonidoScreamer} |`).join('\n')+'\n\nLos archivos se cargan una vez y se reproducen en SOLO, Carrera y Cooperativo según el monstruo. En Cooperativo el sonido de aparición se reproduce en el Vigía que ve el flash. Volumen, silencio y sustos atenuados se aplican mediante el bus de efectos. La música y los efectos de pasos, hojas y latidos siguen en Web Audio.\n\nPuedes sustituir cualquier WAV por tus sonidos conservando la ruta. Si cambias la ruta, actualiza el campo correspondiente en monsters.json. Usa archivos que tengas derecho a utilizar. Incrementa VERSION y los sufijos de recursos al publicar otro conjunto para evitar caché antigua.\n\nGeneración reproducible: python3 tools/generate_audio.py. Código y sonidos originales: puedes usarlos y modificarlos en este proyecto.\n');
const added=monsters.filter(m=>m.id>22);
fs.writeFileSync(new URL('AMPLIACION3.md',root),'# Ampliación 3 · versión 1.2.0\n\n30 monstruos disponibles en el libro, la tira de miniaturas, SOLO, Carrera y Cooperativo. Los 22 retratos previos conservan sus bytes, comprobados por SHA-256. Los ocho retratos nuevos se generaron individualmente con los originales como referencia de estilo: óleo sucio y grabado antiguo, frontal, contraste alto y fondo negro.\n\n## Imágenes nuevas\n\nWebP y PNG de 1024 × 1024. Sin texto ni marcas de agua. El PNG se utiliza si falla el WebP.\n\n| ID | Nombre | WebP | PNG de respaldo |\n|---|---|---|---|\n'+added.map(m=>`| ${m.id} | ${m.nombre} | ${m.imagen} | ${m.imagen.replace('.webp','.png')} |`).join('\n')+'\n\nPrompts de arte: assets/PROMPTS-AMPLIACION3.md. Las descripciones físicas solo están en ese documento de producción, nunca en monsters.json ni en la interfaz.\n\n## Catálogo y pistas\n\nmonsters.json contiene las 30 fichas completas. LORE.md entrega los 30 textos; AUDIO.md contiene los 60 nombres de archivo. tools/validate_lore.mjs valida longitud, nombres, plurales, acentos y sinónimos conocidos.\n\n8 monstruos tienen una debilidad, 12 tienen dos y 10 tienen tres. La unión automática contiene 56 objetos y cada debilidad tiene id, nombre y etiquetaCLIP. El libro muestra retrato, nombre, lore y número de página; el lore reemplaza la lista de debilidades.\n\n## IA y puntuación\n\njs/monsters.js genera la unión; js/ai.js traduce las frases descriptivas devueltas por CLIP a IDs; js/ai-worker.js utiliza las frases con la plantilla. Solo la etiqueta más probable determina el acierto. Confusables no añade aciertos. ?debug=1 muestra top 5 y el grupo de luz y llama.\n\njs/scoring.js usa 400 × min(1, p / PRECISION_REF) con PRECISION_REF = 0.6 en js/config.js. p es la probabilidad ganadora, sin sumar otras debilidades. js/online-game.js recalcula el resultado de Carrera y el Vigía valida el resultado cooperativo con el mismo criterio.\n\n## Leaderboard\n\njs/firebase.js confirma y escribe con IDs estables, lee directamente del servidor y conserva la lectura de registros antiguos sin avatar. js/ui.js muestra errores y reintenta la carga de los tres rankings. SOLO y el podio online permiten reintentar el envío sin duplicar un resultado que ya se guardó.\n\nPublica todos los archivos juntos y las reglas completas de ambas bases. La prueba de producción fue solo de lectura; las escrituras se verifican con el SDK real en emuladores.\n\n## Pruebas\n\nnpm test valida catálogo, 1.680 combinaciones de victoria, lore, imágenes, selección, sonido, dificultad y puntuación. tests/expansion-ui.cjs comprueba libro, PNG, debug, audio y los rankings. tests/ui.cjs recorre tres partidas; tests/online-ui.cjs prueba los dos modos online. El detalle y el checklist están en PRUEBAS.md.\n');
console.log('DOCUMENTOS OK: LORE.md, AUDIO.md y AMPLIACION3.md.');
